### ISSUE TITLE
Custom Elements Example

### ISSUE THREAD

**Issue by lgwaustralia** [bpmn-io/bpmn-js-examples#10]
Just learning how to load custom elements and trying the demo.
Getting Error: Cannot find module 'diagram-js/lib/draw/BaseRenderer' during grunt auto-build.  

I found BaseRenderer.js and dropped it in, but gets errors after grunt auto-build
app.js:20 something went wrong: TypeError: self.createBpmnElement is not a function(…)

PS.Thanks for the great work on bpmn-js / bpmn-io!

**Comment by nikku** [comment]
You need to link the example to the latest diagram-js version because it will be compatible with soon to be released version v0.12.0 only.

```
git clone bpmn-js
git clone diagram-js
cd bpmn-js
npm link ../diagram-js
```
