### ISSUE TITLE
propterties-panel-extension CSS not updated on file changes

### ISSUE THREAD

**Issue by chris-aeviator** [bpmn-io/bpmn-js-examples#100]
When running the `properties-panel-extension` example I can perfectly see the right sidebar and everything works as expected.

Whenever I make a change to any of the files (triggering a bundle update from Grunt) the sidebar's css does not get included anymore and I have to scroll down to see it:

![image](https://user-images.githubusercontent.com/11522213/62599298-0c66e600-b916-11e9-9ec5-374ec25a323a.png)

### Grunt output before the change:
```
$ grunt auto-build
Running "copy:diagram_js" (copy) task
Copied 1 file

Running "copy:bpmn_js" (copy) task
Copied 9 files

Running "copy:app" (copy) task
Copied 3 files

Running "less:styles" (less) task
>> 1 stylesheet created.

Running "browserify:watch" (browserify) task
>> Bundle dist/index.js created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9013

Running "watch" task
Waiting...
```
### Grunt output after the change:

```
updating bundle.
>> File "app/descriptors/magic.json" changed.
Running "copy:app" (copy) task
Copied 3 files

Done.
>> Bundle dist/index.js created.
Completed in 1.034s at Wed Aug 07 2019 13:15:05 GMT+0700 (GMT+07:00) - Waiting..
```

**Comment by pinussilvestrus** [comment]
Was able to reproduce this with editing nearly any file. Seems to be something broken with the grunt configuration.

We are open for contribution 🎉

**Comment by chris-aeviator** [comment]
thanks for your reply! For now it was fine for me as a workaround to copy contents from `dist/app.js` to `app/app.css` since the missing css was anyways static (coming from the `node_modules` directory)
