### ISSUE TITLE
SVG component lost focus when cursor moves to its center

### ISSUE THREAD

**Issue by bungder** [bpmn-io/bpmn-js-examples#102]
It works fine when trying official online demo https://demo.bpmn.io/new
![image](https://user-images.githubusercontent.com/3251115/62944101-94655800-be0e-11e9-8854-b48e5fe43feb.png)

But it behaves differently when trying this demo: https://github.com/bpmn-io/bpmn-js-examples/tree/master/modeler

![image](https://user-images.githubusercontent.com/3251115/62944592-92e85f80-be0f-11e9-961f-2fb39f407e8b.png)

![image](https://user-images.githubusercontent.com/3251115/62945309-15bdea00-be11-11e9-991b-8fab637a5b92.png)

I found out the direct reason, if I change class from "djs-hit" to "djs-hit djs-hit-all" manually in Chrome's dev tool, it will behave just like that online demo.

But why "modeler" examlple sets that class as `djs-hit` without `djs-hit-all`?

How could I fix that?

**Comment by nikku** [comment]
What is your setup? How can we reproduce the issue you're seeing?

**Comment by barmac** [comment]
Please try out once more since we have just updated the libraries in the examples.

**Comment by bungder** [comment]
> Please try out once more since we have just updated the libraries in the examples.

It works. Thanks!

**Comment by bungder** [comment]
> What is your setup? How can we reproduce the issue you're seeing?

@nikku Thanks for replying! Updating diagram-js version from 3.0.1 to 5.0.0 works for me. I think it is the reason.

If you would like to reproduce this issue, here's my setup:

1. `git clone https://github.com/bpmn-io/bpmn-js-examples.git`
2. `cd modeler`
3. `nvm use  v10.16.2`
4. `npm install`
5. `npm run dev`

Since @barmac has updated the libraries in the examples, cloning the newest version of this repository would not reproduce this issue. But rollback to previous commit may do.
