### ISSUE TITLE
XML validation of custom-meta-model

### ISSUE THREAD

**Issue by asoahc** [bpmn-io/bpmn-js-examples#104]
Hi,

I would like to run the integration tests (like bpmn-js-integration) with my bpmn files based on a custom-meta-model. My issue is here that the XML validator is using the standard BPMN20.xsd.

How can I get my model extension into the XSD for validation?
Is there any standard way to extend the BPMN XSD?

Many Thanks in advanced,
Anja

**Comment by nikku** [comment]
What exactly is your setup? What do you do right now?

> How can I get my model extension into the XSD for validation?
> Is there any standard way to extend the BPMN XSD?

This sounds like you're not quite on the right track right now.

As a general rule of thumb you should attempt to extend the BPMN 2.0 in a way that stays compatible with the BPMN20.xsd. Only this way you can ensure interoperability with other tools.

The BPMN standard defines various extension points you can use to do so. If you can / should use them depends highly on your use case, obviously.

**Comment by asoahc** [comment]
Hi Nikku,

you are right. I extended the BPMN 2.0 by using a new task type: genericTask.
genericTask is similar to sendTask: an activity task with additional attributes.
This extension of the bpmn.json follows the custom-meta-model example and runs fine. 

But now I would like to make sure that my created bpmn-files could also be validated against a XML schema. To test the validity I would like to extened bpmn-js-integration modeling and base tests. 
At the moment my tests are failing because there is no genericTask in BPMN20.xsd.

I did not find any solution to extend the BPMN20.xsd with my model extension.
Do you have any idea how can I get all of my extension into a XSD structure.

Many Thanks,
Anja

**Comment by nikku** [comment]
> I did not find any solution to extend the BPMN20.xsd with my model extension.
Do you have any idea how can I get all of my extension into a XSD structure. 

I cannot advice you how to do that. The XSD validation serves the sole purpose of ensuring standard conformity. If you do not need it, you should comment it out / get rid of it.

What I can advice you to is to take [my previous comment](https://github.com/bpmn-io/bpmn-js-examples/issues/104#issuecomment-524078417) into account:

> As a general rule of thumb you should attempt to extend the BPMN 2.0 in a way that stays compatible with the BPMN20.xsd. Only this way you can ensure interoperability with other tools.

You'd need to change the way you implement your BPMN 2.0 extension.

Mark an existing task as special via a certain attribute (i.e. `ext:isGeneric`):

```xml
<bpmn:sendTask ext:isGeneric="true" />
```

Alternatively, you may inline extension elements within a task to mark it as generic, too:

```xml
<bpmn:sendTask>
  <bpmn:extensionElements>
    <ext:genericMetaData>
      <!-- put anything in here -->
    </ext:generigMetaData>
  </bpmn:extensionElements>
</bpmn:sendTask>
```

If you use any of these built-in extension points to extend the BPMN 2.0 XML then you are on the safe side regarding validation.

**Comment by nikku** [comment]
I hope I could provide you with a bit of background information regarding extension implementation.

Closing this issue as _won't fix_.

**Comment by asoahc** [comment]
Hi Nikku,

okay, thank you very much. :)
I didn't look at the situation from this point of view. 
I'll check how much impact a model transformation in that way will have.
