### ISSUE TITLE
Process deployment

### ISSUE THREAD

**Issue by daukadolt** [bpmn-io/bpmn-js-examples#107]
Maybe I've missed something, but does bpmn-js support uploading through engine-rest REST api and if so, how do I use the feature?

**Comment by nikku** [comment]
> Maybe I've missed something

You did not miss anything. bpmn-js is a BPMN 2.0 diagram editor, uploading happens via other tools, e.g. [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch), built into any browser:

```javascript
bpmnJS.saveXML(function(err, xml) {
  if (!err) {
    fetch('/some/backend-url', {
      body: xml
    });
  }
});
```
