### ISSUE TITLE
bpmn 加载后是否可以只读方式显示

### ISSUE THREAD

**Issue by XQCTO** [bpmn-io/bpmn-js-examples#109]

**Comment by philippfromme** [comment]
What is this about?

**Comment by XQCTO** [comment]
> 这是什么意思

我的意思是，加载bpmn文件之后，只读，不可以编辑

**Comment by pinussilvestrus** [comment]
Can you please answer your questions in English? We do not speak Chinese.

**Comment by philippfromme** [comment]
> 我的意思是，加载bpmn文件之后，只读，不可以编辑

So your question is about BPMN?

**Comment by XQCTO** [comment]
yes

**Comment by yfwz100** [comment]
The question that @XQCTO asked is "How to load a read-only model in bpmn-io?".

**Comment by philippfromme** [comment]
Same here: https://github.com/bpmn-io/bpmn-js-examples/issues/110#issuecomment-558966658

**Comment by philippfromme** [comment]
Have a look at this example: https://github.com/bpmn-io/bpmn-js-examples/tree/master/starter
