### ISSUE TITLE
bpmn 保存为svg后，原xml上的方法，如何在svg格式上继续使用   ； 或者说转为svg 后，所关联的参数 、函数方法怎么带出来

### ISSUE THREAD

**Issue by XQCTO** [bpmn-io/bpmn-js-examples#110]

**Comment by pinussilvestrus** [comment]
Please ask your questions in English. We can't speak Chinese.

**Comment by philippfromme** [comment]
Is your question about SVG?

**Comment by linus-amg** [comment]
> _No description provided._

你能用英语问你的问题吗？

**Comment by philippfromme** [comment]
So your question is about BPMN, SVG and XML?

**Comment by XQCTO** [comment]
yes
  my question is about  BPMN and SVG  conversion

**Comment by XQCTO** [comment]
I want to know the methods written on BPMN and how to use them on converted SVG

**Comment by philippfromme** [comment]
> I want to know the methods written on BPMN and how to use them on converted SVG

I don't understand your question. Does it refer to a specific example?

**Comment by yfwz100** [comment]
I try to translate the question that @XQCTO asked:

> How to load bpmn diagram from exported SVG ?

I think it's not possible...

To @XQCTO : SVG is a display format, not a execution format. You may export the original model together with the SVG.

回复 @XQCTO ：SVG 只是一个显示格式，不是执行格式。你可能需要把原有的模型和 SVG 一起导出。

**Comment by philippfromme** [comment]
> How to load bpmn diagram from exported SVG ?

Why would you want to do that?

**Comment by philippfromme** [comment]
Also: This is not the right place to ask questions like this. For general questions about the bpmn.io toolkit please head over to the [forum](forum.bpmn.io). And please ask your question in English.
