### ISSUE TITLE
How to custom a  popup and get data at properties-panel?

### ISSUE THREAD

**Issue by yuwangjuan** [bpmn-io/bpmn-js-examples#111]

**Comment by philippfromme** [comment]
> No description provided.

So what is your question? What example does it refer to?

**Comment by yuwangjuan** [comment]
I need to Customize a pop-up component at properties-panel. But I dont know how to do it.

**Comment by philippfromme** [comment]
For questions please head over to the [bpmn.io forum](https://forum.bpmn.io/). And make sure to provide enough context when asking your question so people will understand it.
