### ISSUE TITLE
Cannot find module 'camunda-bpmn-moddle/resources/camunda.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

### ISSUE THREAD

**Issue by hiraghuak** [bpmn-io/bpmn-js-examples#117]
Angular 8

Unable to import "camunda-bpmn-moddle/resources/camunda.json", getting error 

" ERROR in src/app/app.component.ts(19,37): error TS2732: Cannot find module 'camunda-bpmn-moddle/resources/camunda.json'. Consider using '--resolveJsonModule' to import module with '.json' extension
    src/app/app.component.ts(34,4): error TS2554: Expected 2 arguments, but got 1.
"
**app.components.ts**

`import {  AfterContentInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  ViewChild,
  SimpleChanges,
  EventEmitter } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

import Modeler from 'bpmn-js/lib/Modeler.js';
import propertiesPanelModule from 'bpmn-js-properties-panel';
import propertiesProviderModule from 'bpmn-js-properties-panel/lib/provider/camunda';

// import * as camundaModdleDescriptor from 'node_modules/camunda-bpmn-moddle/resources/camunda.json';
import camundaModdleDescriptor from 'camunda-bpmn-moddle/resources/camunda.json';

// import camundaModdleDescriptor from 'camunda-bpmn-moddle/resources/camunda.json';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent{
  title = 'Workflow Modeler';
  modeler: Modeler;

  @ViewChild('canvas')
  private canvesRef: ElementRef;

  constructor(private http: HttpClient) {
  }

  ngOnInit(): void {
    this.modeler = new Modeler({
      container: '#canvas',
      width: '100%',
      height: '600px',
      propertiesPanel: {
        parent: '#properties'
      },
      additionalModules: [
        propertiesPanelModule,
        propertiesProviderModule
      ],
      moddleExtensions: {
        camunda: camundaModdleDescriptor
      }
    });
    this.load();
  }

  load(): void {
    this.getExample().subscribe(data => {
      this.modeler.importXML(data, value => this.handleError(value));
    });
  }

  handleError(err: any) {
    if (err) {
      console.warn('Ups, error: ', err);
    }
  }

  public getExample(): Observable < string > {
    const url = '/assets/bpmn/initial.bpmn';
    return this.http.get(url, { responseType: 'text' });
  }
}`

![image](https://user-images.githubusercontent.com/17245017/90142787-6f495380-dd9a-11ea-89f9-c09e01642d54.png)

**Comment by pinussilvestrus** [comment]
1. In the future, [please format your code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting). It's incredibly hard to help you when it's hard reading your code.
2. Please head to [our forum](https://forum.bpmn.io/) when you have trouble in starting on of our tools. This site here should be used for bugs and feature requests. Your issue does not seem to be related with any of our examples.
