### ISSUE TITLE
Dockerize modeler example

### ISSUE THREAD

**Issue by rvangala936** [bpmn-io/bpmn-js-examples#121]
Hello,
 Is there a way to dockize the modeler example? Example works fine but when run inside the docker container, app is not accessible from outside the container!

Any ideas on how to make this accessible while running in a docker container ?

Thanks
Ravi

**Comment by nikku** [comment]
Which example do you refer to? Do you plan to dockerize building or serving an example? 

Whatever examples we provide here are plain old HTML _or_ trivial web servers. From what it sounds like I assume that you got an issue with the way you dockerize things.

**Comment by MaxTru** [comment]
@rvangala936 the typical issue when the web server is not reachable from outside the Docker container is that the `--host 0.0.0.0` option was not supplied. Please see https://forum.bpmn.io/t/how-to-run-bpmn-js-app-in-a-docker-container/5126/5?u=maxtru

**Comment by rvangala936** [comment]
@MaxTru  Thank you very much for the help.
