### ISSUE TITLE
Dont unterstand diagram-js-minimap install

### ISSUE THREAD

**Issue by BRaymond69** [bpmn-io/bpmn-js-examples#122]
Hello to you, I'm currently installing BPMN on my Pc (debian 9), so I downloaded BPMN-JS, do an installation : download bpmn-js then npm install and modeler.html also to have a graphic rendering on a web page:
(https://github.com/bpmn-io/bpmn-js-examples/blob/61ccfb8727fe7c34bcf48094222fac292a12ca9c/starter/modeler.html)

I would like to add some specificities to the BPMN-Js like for example diagram-js-minimap, when you go to the github page it's not very precise (or it's me who misunderstands)
how to add diagram-js-minimap?
Is it necessary to create a js script at the root of the folder, is it necessary to add the code given in a folder or file or in the modeler.html ?

**Comment by philippfromme** [comment]
There is a dedicated example of adding the minimap: https://github.com/bpmn-io/bpmn-js-examples/tree/master/minimap Have you seen that?

**Comment by BRaymond69** [comment]
Thankes for you response.
Yes, I've seen it, but I don't know how I integrate this into bpmn-js (where am I supposed to integrate this part of the code?)

because I followed the bpmn-js installation guide.

cd bpmn-js
npm install
npm run all

To get started, create a bpmn-js instance and render BPMN 2.0 diagrams in the browser:
And the following code.
I don't understand this sentence, I need to add it to an existing HTML page or I need to create it from scratch.

**Comment by philippfromme** [comment]
I don't understand your question. The minimap example bootstraps a bpmn-js modeler including the minimap. What's missing?

**Comment by MaxTru** [comment]
Since this is more a question than an issue (also see [this thread](https://forum.bpmn.io/t/add-diagram-js-minimap-to-the-bpmn-js/5305/2)), I am closing this issue. Please follow up [here](https://forum.bpmn.io/t/add-diagram-js-minimap-to-the-bpmn-js/5305/2)

**Comment by BRaymond69** [comment]
sorry I may have misspoke.
First I downloaded the bpmn-js folder via git, comes the first problem where (in which file or folder) should I include the js code from the Usage part (because I don't understand what it's for) it's the same for the Dynamic Attach/Detach.

after building the project, I would like to add diagram-js-minimap but I haven't already understood the basis of the project so I don't know if you can enlighten me
