### ISSUE TITLE
Cannot install Properties Panel Extension Example

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [bpmn-io/bpmn-js-examples#128]
__Describe the Bug__
Executing `npm install` for the [Properties Panel Extension Example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) results in the following error:

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bpmn-js-example-properties-panel-extension@0.0.0
npm ERR! Found: bpmn-js@8.2.0
npm ERR! node_modules/bpmn-js
npm ERR!   bpmn-js@"^8.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer bpmn-js@"^3.x || ^4.x || ^5.x || ^6.x || ^7.x" from bpmn-js-properties-panel@0.37.6
npm ERR! node_modules/bpmn-js-properties-panel
npm ERR!   bpmn-js-properties-panel@"^0.37.6" from the root project

__Steps to Reproduce__

1. Clone the repository.
2. Execute `npm install` in the directory properties-panel-extension.
3. The error is thrown.

__Expected Behavior__

The command should go through without errors, allowing me to run the example.

__Environment__

- Node version: v15.8.0
- NPM version: 7.5.4
- OS: Linux Mint 19.3
- Library version: 8.2.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting!

[Since npm@7 is now generally available](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) we should ensure our peer-dependencies are met.
