### ISSUE TITLE
'get' on proxy: property '$pkg' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')

### ISSUE THREAD

**Issue by jsliu27** [bpmn-io/bpmn-js-examples#132]
__Describe the Bug__
'get' on proxy: property '$pkg' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')

1. git clone https://github.com/jsliu27/bpmn_demo.git
2. cd bpmn_deo
3. npm i
4. npm run dev
5. http://localhost:8080/#/base

__Steps to Reproduce__

1. do this
2. do that
3. now this happens

__Expected Behavior__

No error
__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS] Chrome 89
- OS: [e.g. Windows 7] mac OS
- Library version: [e.g. 2.0.0] 8.3.0

**Comment by philippfromme** [comment]
Closed in favor of https://github.com/bpmn-io/bpmn-js/issues/1433.
