### ISSUE TITLE
Update examples to fit new properties panel architecture

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-examples#135]
__What should we do?__

Once we release the `v1.0.0` version of the new Properties Panel, we shall also update the existing examples:

* [x] #145
* [x] Update [`/properties-panel-extension`](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension)
* [x] #148
* [ ] Feature the following use-cases
    * [ ] Replace individual form components
    * [ ] Add additional form components

We already started with a minimal example inside the [`properties-panel-next-example`](https://github.com/bpmn-io/bpmn-js-examples/tree/properties-panel-next-example) branch. To avoid confusion with the old, but still available properties panel integration, let's follow up with the update once we reach the point of releasing the whole properties panel as `bpmn-js-properties-panel@1.0.0`.

__Why should we do it?__

Showcase the usage of the new properties panel.

**Comment by pinussilvestrus** [comment]
> One new example to show case the capabilities of the new architecture (e.g. async data fetching)

One example we could consider when working on this: https://github.com/pinussilvestrus/properties-panel-async-example

/cc @barmac

**Comment by nikku** [comment]
This is mostly done (all examples use new architecture).
