### ISSUE TITLE
API doc We need it

### ISSUE THREAD

**Issue by ZxBee** [bpmn-io/bpmn-js-examples#136]
__Is your feature request related to a problem? Please describe__

__Describe the solution you'd like__

__Describe alternatives you've considered__

__Additional context__

**Comment by pinussilvestrus** [comment]
Could you please provide the necessary information? Otherwise, we can't help you. Thanks!

**Comment by pinussilvestrus** [comment]
@ZxBee any updates on this? Otherwise, we will likely close it without the necessary details.
