### ISSUE TITLE
[custom-modeler] Move not working for BPMN shapes

### ISSUE THREAD

**Issue by calbertts** [bpmn-io/bpmn-js-examples#14]
In the example to create custom elements, the custom modeler seems not to be applying the drag and drop event for BPMN shapes.

I've tested this with both, and the drag and drop works with the Modeler by default, but once I start to use the custom one the drag and drop events stop working for BPMN shapes.

I found that the problem comes from this file: **CustomRules.js** in the line **53**

Seems that if you try to move a custom element the `allowed` variable is true, but if it's a BPMN shape is false.

I'm not looking deeply into this issue, as a workaround, now I'm returning `true` always, but I'm not sure what it implies.

There's an small explanation in a comment before that line, maybe I'm not understanding the right behavior of this.

**Comment by nikku** [comment]
Good catch!

I thought that was the intended behavior of the example but judging from the comment before the blog I guess I was wrong. :grinning:

I am going to change it in a way that the actual behavior corresponds with the comment (i.e. allow move but do not allow mixed movements).

Nice if always returning `true` works for you. It is ment to be an example for people to continue hacking on anyway.
