### ISSUE TITLE
An uncaught exception on the dev console for colors example

### ISSUE THREAD

**Issue by fred104** [bpmn-io/bpmn-js-examples#141]
__Describe the Bug__

When you open the sample html under colors folder (./colors/index.html), you will see an uncaught exception on the console.

__Steps to Reproduce__

1. Open chrome dev tools
2. Open `./colors/index.html`
3. An uncaught exception shows on the console. Option 2 (Color via BPMN 2.0 Extension) and Option 3 (Color via Marker + CSS Styling) are not working due to this exception.

__Expected Behavior__

The exception should not show. I tried to trace it. It seems that `colorToHex` under `bpmn-modeler` can't convert `'rgba(0, 80, 0, 0.4)'` to correct hex code. 

__Environment__

- Host: Chromium 93.0.4577.58 
- OS: Mac
- Library version: bpmn-js@8.8.3

**Comment by nikku** [comment]
Thanks for the heads-up. Likely we need to apply a small fix to the example. 

We'll look into the issue.
