### ISSUE TITLE
How can I add custom element?

### ISSUE THREAD

**Issue by soulmate2015** [bpmn-io/bpmn-js-examples#15]
I want to add a element `name` like this:
```javascript
<bpmn:startEvent id="_2" name="MyStart">
    ...
</bpmn:startEvent>
```
How to revise the js-properties-panel and add custom element and value.

**Comment by nikku** [comment]
You are currently not able to change an elements name via the properties panel.

I opened bpmn-io/bpmn-js-properties-panel#124 which should add this functionality.

You can always edit an elements name by double-clicking it on the canvas.

Please comment, if this did not answer your question.
