### ISSUE TITLE
Error in vue

### ISSUE THREAD

**Issue by polarloves** [bpmn-io/bpmn-js-examples#150]
hello!

when i use  bpmn-js-examples/properties-panel-extension in vue ,an error happend, how should i use it?

![image](https://user-images.githubusercontent.com/11882911/148521412-2bebc39b-4cb8-4c19-9247-1a5e72aba984.png)

**Comment by marstamm** [comment]
Hi @polarloves ,

please use the Bug Report template so we can help you more efficiently. https://github.com/bpmn-io/.github/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

It also helps of you share a running / prototypical example that clearly shows what you’re trying to achieve, what is working and what is not.

Use our existing starter projects to quickly hack it or share your existing, partial solution on GitHub or via a CodeSandbox. Provide the necessary pointers that allow us to quickly understand where you got stuck.

This way we may be able to help you in a constructive manner.

Thanks

**Comment by pinussilvestrus** [comment]
Any updates on this one @polarloves?

**Comment by polarloves** [comment]
> Any updates on this one @polarloves?

i solved this problem,because there is no babel  module in my project,thanks!

**Comment by minzhenyu** [comment]
@polarloves  i have the same problem, can u show me your config?
