### ISSUE TITLE
How to add moddleExtension for Custom Bundle?

### ISSUE THREAD

**Issue by sasupe** [bpmn-io/bpmn-js-examples#154]
Hello,
Thanks for the awesome tool!

How do we add 'moddleExtension' when creating a custom bundle? I understood how to add a custom module but couldn't find how to add a 'moddleExtension' for custom bundle.

For e.g. including line 32 linked below for a customBundle similar to adding customModules as done in L22 to L31 linked below.
https://github.com/bpmn-io/bpmn-js-examples/blob/e0ee91c25f17bdd43708ea2d6366189634a92884/properties-panel-extension/app/index.js#L32

https://github.com/bpmn-io/bpmn-js-examples/blob/e0ee91c25f17bdd43708ea2d6366189634a92884/custom-bundle/src/custom-viewer.js#L22-L31

Thanks

**Comment by philippfromme** [comment]
Hey,

adding a model extension is described in this example: https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-meta-model

Does this answer your question?

**Comment by sasupe** [comment]
Hi @philippfromme,
The example covered adding a custom module, but not 'ModdleExtension' for the moddle. 

In the properties extension example,
https://github.com/bpmn-io/bpmn-js-examples/blob/e0ee91c25f17bdd43708ea2d6366189634a92884/properties-panel-extension/app/index.js#L21-L34

additional modules are added on L27-L29 but there is also an additional moddleExtension `magic: magicModdleDescriptor` on L32

So, my question was how to wrap the moddleExtension in a custom package.

**Comment by nikku** [comment]
Sorry for the late response. 

I'm still not 100% sure what you need. But overriding / providing `_moddleExtensions` via the prototype or overriding [`BpmnViewer#_createModdle`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseViewer.js#L667) should do the trick. Pick either option.
