### ISSUE TITLE
Update properties panel examples to the new API

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-examples#160]
__What should we do?__

Update examples to account for breaking changes in https://github.com/bpmn-io/properties-panel/pull/134

* [ ] Update https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension
* [ ] Update https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-async-extension

__Why should we do it?__

The examples should be up to date.

---

Related to https://github.com/bpmn-io/bpmn-js-examples/issues/135

**Comment by pinussilvestrus** [comment]
Thanks for creating this issue 👍 
Another thing to update: https://github.com/bpmn-io/properties-panel-async-example, which I can take care of.

Cf. https://github.com/bpmn-io/properties-panel-async-example/issues/2

**Comment by MaxTru** [comment]
We will do this, after we released 1.0.0 stable

**Comment by Adrian-Bielefeldt** [comment]
When I try to run `npm install` in [properties-panel-extension](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) I get the following error:
```
npm ERR! Could not resolve dependency:
npm ERR! peer @bpmn-io/properties-panel@"0.11.x" from bpmn-js-properties-panel@1.0.0-alpha.5
npm ERR! node_modules/bpmn-js-properties-panel
npm ERR!   bpmn-js-properties-panel@"^1.0.0-alpha.0" from the root project
```
Am I correct in assuming a relation to this issue? Or is that a separate problem that I should report?

**Comment by MaxTru** [comment]
> When I try to run `npm install` in [properties-panel-extension](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) I get the following error:
> 
> ```
> npm ERR! Could not resolve dependency:
> npm ERR! peer @bpmn-io/properties-panel@"0.11.x" from bpmn-js-properties-panel@1.0.0-alpha.5
> npm ERR! node_modules/bpmn-js-properties-panel
> npm ERR!   bpmn-js-properties-panel@"^1.0.0-alpha.0" from the root project
> ```
> 
> Am I correct in assuming a relation to this issue? Or is that a separate problem that I should report?

Hi @Adrian-Bielefeldt ,

thanks for spotting! Could you please report a seperate issue? I think this is something we can/should fix even before doing this issue here.

Thanks!

**Comment by pinussilvestrus** [comment]
> Could you please report a seperate issue?

I think this has now already been reported 🙂 
https://github.com/bpmn-io/bpmn-js-examples/issues/162
