### ISSUE TITLE
properties-panel-extension does not work with new bpmn-js-properties-panel version

### ISSUE THREAD

**Issue by Vincenzo1409** [bpmn-io/bpmn-js-examples#162]
We are trying to update our camunda modeler plugins with the new properties-panel version (1.0.0-alpha.0) but we got back "Could not resolve dependency" error.

When I run the command `npm install` in [properties-panel-extension](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) I get the following error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer @bpmn-io/properties-panel@"0.11.x" from bpmn-js-properties-panel@1.0.0-alpha.5
npm ERR! node_modules/bpmn-js-properties-panel
npm ERR! bpmn-js-properties-panel@"^1.0.0-alpha.0" from the root project

```

I expect there are no conflicts between versions and the code to compile properly.

I'm using the following configuration regarding dependency versions:
```
"bpmn-io/properties-panel": "^0.10.0",
"bpmn-js": "^9.0.2",
"bpmn-js-properties-panel": "^1.0.0-alpha.0",

```
I also tried with other dependencies version like "bpmn-io/properties-panel": "^0.11.0" or "bpmn-js-properties-panel": "^1.0.0-alpha.5", and different combinations taking point from token simulation plugin package.json but the results were the same.

**Comment by pinussilvestrus** [comment]
Thanks for reporting! We already have tracked to update the example to the latest versions: https://github.com/bpmn-io/bpmn-js-examples/issues/160#issuecomment-1056512189

In the meanwhile, you could pin the version to not choose the latest alpha. As an example

```json
"@bpmn-io/properties-panel": "0.10.0",
"bpmn-js-properties-panel": "1.0.0-alpha.4",
```

Does this help you as a workaround?

**Comment by Vincenzo1409** [comment]
> Thanks for reporting! We already have tracked to update the example to the latest versions: [#160 (comment)](https://github.com/bpmn-io/bpmn-js-examples/issues/160#issuecomment-1056512189)
> 
> In the meanwhile, you could pin the version to not choose the latest alpha. As an example
> 
> ```json
> "@bpmn-io/properties-panel": "0.10.0",
> "bpmn-js-properties-panel": "1.0.0-alpha.4",
> ```
> 
> Does this help you as a workaround?

I just tried with the configuration you suggested but I got the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bpmn-js-example-properties-panel-extension@0.0.0
npm ERR! Found: @bpmn-io/properties-panel@0.10.2
npm ERR! node_modules/@bpmn-io/properties-panel
npm ERR!   @bpmn-io/properties-panel@"^0.10.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @bpmn-io/properties-panel@"0.11.x" from bpmn-js-properties-panel@1.0.0-alpha.5
npm ERR! node_modules/bpmn-js-properties-panel
npm ERR!   bpmn-js-properties-panel@"^1.0.0-alpha.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by pinussilvestrus** [comment]
Just to verify, did you clean up your node modules (`npm ci`, or `rm -rf node_modules && npm i`)?

**Comment by Vincenzo1409** [comment]
> Just to verify, did you clean up your node modules (`npm ci`, or `rm -rf node_modules && npm i`)?
> 
> Which npm / node version do you use?

Yes, I did wipe out node modules. 
I'm using the following combination of npm/node: 
```
node version: 16.13.1
npm version: 8.1.2
```

**Comment by pinussilvestrus** [comment]
Did try out another alpha versions of `bpmn-js-properties-panel`?

**Comment by Vincenzo1409** [comment]
Yes, I tried all versions from 1.0.0-alpha.0 to 1.0.0-alpha.5 and I got the same error.

**Comment by Ichigo85** [comment]
Hello @pinussilvestrus ,
I just tried your solution, I downgraded node and npm and the command `npm install` finally works, but there's another problem now. 
I made some tests:
Using these versions
```
"@bpmn-io/properties-panel": "0.10.0",
"bpmn-js-properties-panel": "1.0.0-alpha.4",
```
If I run the example and create a really simple diagram, the properties panel is completely stuck from the start.  It doesn't respond to any interaction, and there's this error on console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'is')
    at j (index.js:3184:6847)
    at I (index.js:3184:6240)
    at m (index.js:3184:2155)
    at j (index.js:3184:7266)
    at I (index.js:3184:6240)
    at m (index.js:3184:2155)
    at j (index.js:3184:7266)
    at I (index.js:3184:6240)
    at m (index.js:3184:2155)
    at I (index.js:3184:6058)
```

If I, instead, upgrade both versions to 
```
"@bpmn-io/properties-panel": "0.11.0",
"bpmn-js-properties-panel": "1.0.0-alpha.5",
```
the panel properties gets stuck only when clicking on the start element, returning this error:
```
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at j (http://localhost:5000/index.js:3217:6829)
    at I (http://localhost:5000/index.js:3217:6240)
    at m (http://localhost:5000/index.js:3217:2155)
    at j (http://localhost:5000/index.js:3217:7266)
    at I (http://localhost:5000/index.js:3217:6240)
    at m (http://localhost:5000/index.js:3217:2155)
    at j (http://localhost:5000/index.js:3217:7266)
    at I (http://localhost:5000/index.js:3217:6240)
    at m (http://localhost:5000/index.js:3217:2155)
    at I (http://localhost:5000/index.js:3217:6058)
```

Fun fact: I tried bpmn-js-token-simulation adding magic.json and SpellProps, with node@16 and npm@8 and everything worked fine. Now it does not work anymore and I can't make it work again 😅

What is happening?

**Comment by pinussilvestrus** [comment]
> What is happening?

Since we are now in __alpha stage__ of the new properties panel, there are likely breaking changes until we get stable. For example, in `@bpmn-io/properties-panel` version 0.11 we [changed the entries from being elements to components](https://github.com/bpmn-io/properties-panel/blob/main/CHANGELOG.md#breaking-changes). 

The examples are not updated yet. We have it on our list, though: https://github.com/bpmn-io/bpmn-js-examples/issues/160. Until, If you want to work with the latest versions you would have to [make the updates on your own](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/CHANGELOG.md#breaking-changes).

In the meanwhile, it is kind of expected that the examples crash, especially when using other / the latest alpha versions.

**Comment by Ichigo85** [comment]
I knew it's an alpha stage, It wasn't a real question, sorry.
I think I will probably wait for the next version then. Thank you for your help!

**Comment by pinussilvestrus** [comment]
Thanks for reaching out 👍 

I will move this one to the backlog, let's refine it once we [updated the examples](https://github.com/bpmn-io/bpmn-js-examples/issues/160).
