### ISSUE TITLE
How to set the external label color using addMarker

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js-examples#165]
How to set the external label color using addMarker
<img width="417" alt="image" src="https://user-images.githubusercontent.com/62740686/159390925-6d8505d0-c1b0-4ff0-be7d-6ab815d1dd15.png">

**Comment by smbea** [comment]
Could you please use our [issue templates](https://github.com/bpmn-io/diagram-js/issues/new/choose) to provide the necessary information? In case no template is fitting, probably [the forum](https://forum.bpmn.io/) would be a better place to ask your question.

**Comment by barmac** [comment]
Closing this as the forum is right place to ask such questions as @smbea suggested.
