### ISSUE TITLE
Implement modeler in VueJS

### ISSUE THREAD

**Issue by WaleedAbu-Nafiseh** [bpmn-io/bpmn-js-examples#167]
I am Trying to integrate the modeler in a vue application. I was wondering if it is possible to have an example for this/ gather interest in such an example? 
@nikku, might be best to get you involved.

**Comment by nikku** [comment]
Does [`vue-bpmn`](https://github.com/bpmn-io/vue-bpmn) serve as an appropriate example? If not, contributions welcome.
