### ISSUE TITLE
BPMN-JS Properties Panel Extension Plugin Example Not working

### ISSUE THREAD

**Issue by billbarni** [bpmn-io/bpmn-js-examples#169]
__Describe the Bug__

I can't build the project, properties panel Alpha not found. If I upgrade to an existing version the projectr builds but it does not work when added to the plugin directory of the modeler with the default recommended index.js:

import {
  registerBpmnJSModdleExtension,
  registerBpmnJSPlugin
} from 'camunda-modeler-plugin-helpers';
import magicPropertiesProviderModule from './provider/magic/index';
import magicModdleDescriptor from './descriptors/magic.json';

registerBpmnJSModdleExtension(magicModdleDescriptor);
registerBpmnJSPlugin(magicPropertiesProviderModule);

__Steps to Reproduce__

1. build
2. copy dist to Modeler plugin folder
3. nothing happens

__Expected Behavior__

properties panel shows the desired fields

__Environment__

- Camunda Modeler >= 4.12

**Comment by pinussilvestrus** [comment]
Hi @billbarni, which version of the Camunda Modeler do you use (4.12 or 5.0)? That makes a difference as the current version of the[ properties panel extension](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) is not compatible with Modeler version < 5.

**Comment by pinussilvestrus** [comment]
Any updates on this one @billbarni ?

**Comment by pinussilvestrus** [comment]
I'm closing this now due to inactivity. Feel free to re-open 👍
