### ISSUE TITLE
Unable to place Pool/Participant

### ISSUE THREAD

**Issue by FinallyCanuck** [bpmn-io/bpmn-js-examples#176]
__Describe the Bug__

When I attempt to Create a Pool/Participant on an existing diagram, the object overwrites the diagram and the mouse cursor freezes prevent any further action.

__Steps to Reproduce__

1. Create basic diagram with a few tasks and a pair of gateways.
2. Click Create Pool/Participant
3. The Pool is 'grabbed' and I place it on my diagram
4. The diagram I placed the pool on disappears and the mouse locks holding another instance of the pool for me to place.
5. I can't perform any other actions after this.

__Expected Behaviour__

When I click Create Pool/Participant, I should be able to place it on the diagram canvas either framing the existing diagram or adjacent to it.

__Environment__

- Host (Browser/Node version), if applicable: MS Edge Version 103.0.1264.44 (Official build) (64-bit)
- OS: Windows 10
- Library version: bpmn-js 9.2.2

**Comment by barmac** [comment]
Does it happen in any particular example? Can you reproduce it at https://demo.bpmn.io/?

**Comment by FinallyCanuck** [comment]
I can't reproduce it on https://demo.bpmn.io/. However, I was able to reproduce it on the demo on https://cdn.staticaly.com/gh/bpmn-io/bpmn-js-examples/master/starter/modeler.html (on the modeler starter).

Is there an option to clone the demo.bpmn.io version for local hosting?

**Comment by Skaiir** [comment]
I also cannot reproduce, 

Window 10 64bit
MS Edge Version 103.0.1264.44

**Comment by FinallyCanuck** [comment]
https://user-images.githubusercontent.com/10479763/177757283-61669b82-4235-418b-b0b2-65156564f181.mp4

See the attached screen capture. The only changes I've made to the Modeller starter is changing the font family and adding a header.

**Comment by nikku** [comment]
We cannot reproduce this on our end; either you allow us to reproduce it (provide an example we can try out) or you provide additional information, i.e. DevTools (`F12`) output.

Otherwise we'd need to close this as `invalid`.

**Comment by FinallyCanuck** [comment]
I have found a different solution to what I'm trying to accomplish. Closing this issue.
