### ISSUE TITLE
Please add keyboard bindTo: window to the modeler example

### ISSUE THREAD

**Issue by agileadam** [bpmn-io/bpmn-js-examples#178]
https://github.com/bpmn-io/bpmn-js-examples/blob/baa45fa17be5e67fd31f56d54f21453883d559ce/modeler/app/app.js#L10

Hello, I have a simple request. Can you please include the keyboard bindings in the modeler example? It took me a while to track down why I couldn't use my keyboard to move elements, undo, redo, change tools, etc. I thought it was because I was using the wrong versions of the library(s) or something. I was simply missing the keyboard config.
Thanks!

Before:
```
var modeler = new BpmnModeler({
  container: '#js-canvas',
});
```

After:
```
var modeler = new BpmnModeler({
  container: '#js-canvas',
  keyboard: {
    bindTo: window
  }
});
```

**Comment by nikku** [comment]
Good catch. Would you like to contribute that improvement?
