### ISSUE TITLE
Improvement to custom-elements example

### ISSUE THREAD

**Issue by baardl** [bpmn-io/bpmn-js-examples#18]
Hi.

When I ran the custom-elements example, then I ran into this issue:
> ..../bpmn-js-examples/custom-elements: grunt auto-build
Running "browserify:watch" (browserify) task
Warning: watch ..../bpmn-js-examples/custom-elements/node_modules/lodash/internal/createHybridWrapper.js ENOSPC Use --force to continue.
Aborted due to warnings.

Then I ran this code:
> ..../bpmn-js-examples/custom-elements$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

After which 
> grunt auto-build 

works like a swell.

Found the solution here http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by nikku** [comment]
Thanks for pointing this out. I added it to our [developer FAQ](https://forum.bpmn.io/t/developer-faq-bpmn-js/282) in the forum.

I guess anyone of us had to configure this at least once already.

**Comment by baardl** [comment]
Thanks for quick reply, Nikku.

Might be a good idea to add that to the readme.md as well?

Best regards
Bård

**Comment by nikku** [comment]
I updated the issue with a more descriptive title so that people searching for it will find it.
