### ISSUE TITLE
Task/Bugfix: Update "diagram-js": to "^8.9.0" in `modeler` example.

### ISSUE THREAD

**Issue by mhsdesign** [bpmn-io/bpmn-js-examples#182]
__What should we do?__

Update "diagram-js": to "^8.9.0" in `modeler` example.
https://github.com/bpmn-io/bpmn-js-examples/blob/28ae32f4a05ec1586c3f8072171b0e468c8cf794/modeler/package.json#L42

__Why should we do it?__

Otherwise the demo is a bit broken see https://github.com/bpmn-io/bpmn-js/issues/1683

**Comment by pinussilvestrus** [comment]
Thanks for reporting! I updated it accordingly via https://github.com/bpmn-io/bpmn-js-examples/commit/ca8da0b13779ba18fb926314253ee7ce5460a8ec
