### ISSUE TITLE
properties panel example should work without JSX

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js-examples#206]
__What should we do?__
Change https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension to not use JSX.

E.g.: use `htm` instead.

__Why should we do it?__

- When using the example in a React/Angular/..., the JSX is compiled by the root application
- This is a reoccurring issue in the forum. It hinders the getting started experience

----

Related to https://github.com/bpmn-io/bpmn-js-examples/issues/200

**Comment by chilligerchief** [comment]
This actually hinders me from extending the properties panel in my svelte application. Do you have a working example without JSX? Or can you provide a link to the forum, where someone got it to work?

**Comment by nikku** [comment]
You can use tagged template literals to accomplish the same thing, no JSX required. Please checkout https://github.com/developit/htm and see if that helps you.

We aim to port this example over, but were simply not able to do so, yet.

**Comment by chilligerchief** [comment]
This works fine. However, I wonder if there is a way to do this without adding yet another dependency. But I guess this is the way the world of javascript has evolved.

**Comment by nikku** [comment]
You can absolutely do without an additional dependency. But it will be verbose / impossible to maintain.

**Comment by marstamm** [comment]
Hi @hknsrr ,

sorry for the late reply. There are multiple ways to create Preact components. If you don't want to use JSX, an alternative could be `htm`. Check out the changes in #240 to see how this would look like.
