### ISSUE TITLE
TypeError while trying to add a custom property to Service Tasks

### ISSUE THREAD

**Issue by SundaramMaheshkumar** [bpmn-io/bpmn-js-examples#209]
__TypeError while trying to add a custom property to Service Tasks__

I am trying to customize [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) according to this example [here](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension).

I am trying to add a custom property `destination` to all the service tasks.

[__Codesandbox__](https://codesandbox.io/s/bpmn-prop-tabs-removal-nj39ik)

__Steps to Reproduce__

1. When the modeller launches, add a start event
2. Then try to add a service task
3. TypeError Occurs

__Error__

![image](https://user-images.githubusercontent.com/118889895/208460338-8e0f32ba-217a-4725-80df-f6acf9a3303a.png)

__Libraries & versions__

- @bpmn-io/properties-panel": "1.1.0"
- "bpmn-js": "11.1.0"
- "bpmn-js-properties-panel": "1.14.0"

Thanks!

**Comment by nikku** [comment]
Looking into your sandbox I see that you attempt to build your extension using React. 

This is not a use-case we support. As seen [in the example](https://github.com/bpmn-io/bpmn-js-examples/blob/master/properties-panel-extension/webpack.config.js#L26) you want to make sure that the extension uses `@bpmn-io/properties-panel/preact` as an import source. In addition you would want to ensure that you load hooks and friends from the same export:

```javascript
import { useState } from '@bpmn-io/properties-panel/preact/hooks';

...
```
