### ISSUE TITLE
Be able to export and import color settings in bpmn annotation

### ISSUE THREAD

**Issue by jobburg** [bpmn-io/bpmn-js-examples#21]
It would be nice if you guys added the function to import/export shapes with color attributes like border color.

**Comment by nikku** [comment]
Are you requesting a feature? If that is the case, please open a ticket in the respective project repository (i.e. [bpmn-js](https://github.com/bpmn-io/bpmn-js).

Be descriptive about what you are trying to achieve and why.

**Comment by jobburg** [comment]
@nikku Indeed I am requesting a feature. I want to be able to import and export shapes and relations with colors for readability purposes at large diagrams.
