### ISSUE TITLE
adding new connector and draw it with 'CHANGE ELEMENT'

### ISSUE THREAD

**Issue by TaheriSohrab** [bpmn-io/bpmn-js-examples#224]
![vite](https://user-images.githubusercontent.com/51846650/221777069-f22d719b-c3eb-41fd-965c-72f230a2ca50.png)

Hi, how u doing?
I'm involving with that for months..... is it possible?
I have no idea about it and too pressure on me...

**Comment by nikku** [comment]
Did you raise this issue in the [project forum](https://forum.bpmn.io/)? Let's get it solved over there.

**Comment by nikku** [comment]
Raised in [forum](https://forum.bpmn.io/t/can-we-add-custom-element-and-shape-for-drawing/8885).
