### ISSUE TITLE
add listGroup to properties-panel in Camunda

### ISSUE THREAD

**Issue by wsochoa** [bpmn-io/bpmn-js-examples#227]
### Is your feature request related to a problem? Please describe.

Hello! I'm struggling a bit with adding a custom group inside the properties panel. I'm following this tutorial: https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-list-extension This explains exactly what I want to achieve. However, it doesn't work for Camunda Modeler.  I know the example is for bpmn-io, but it would be nice to add a new section with the specific steps to reproduce it in Camunda Modeler.

If you could help me with some hints to bypass this error would be also nice. The error I'm facing is:
`hooks.module.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__H')
    at m (hooks.module.js:1:1)
    at d (hooks.module.js:1:1)
    at s (hooks.module.js:1:1)
    at g.ListGroup [as constructor] (index.esm.js:970:1)
    at g.R [as render] (preact.module.js:1:8050)
    at S (preact.module.js:1:5825)
    at w (preact.module.js:1:2155)
    at M (preact.module.js:1:7266)
    at S (preact.module.js:1:6240)
    at w (preact.module.js:1:2155)
m @ hooks.module.js:1
d @ hooks.module.js:1
s @ hooks.module.js:1
ListGroup @ index.esm.js:970
R @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
M @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
M @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
S @ preact.module.js:1
w @ preact.module.js:1
S @ preact.module.js:1
(anonymous) @ preact.module.js:1
E @ preact.module.js:1
Promise.then (async)
v @ preact.module.js:1
g.setState @ preact.module.js:1
X.r.__c.r.__ @ hooks.module.js:1
d @ index.esm.js:1343
e @ index.esm.js:1363
(anonymous) @ EventBus.js:519
ke._invokeListener @ EventBus.js:371
ke._invokeListeners @ EventBus.js:352
ke.fire @ EventBus.js:313
Kt.select @ Selection.js:106
(anonymous) @ SelectionBehavior.js:99
(anonymous) @ EventBus.js:519
ke._invokeListener @ EventBus.js:371
ke._invokeListeners @ EventBus.js:352
ke.fire @ EventBus.js:313
s @ InteractionEvents.js:94
f.<computed> @ InteractionEvents.js:173
(anonymous) @ index.esm.js:359`

The error occurs in the ListGroup constructor (@bpmn-io/properties-panel), exactly in this line: `const groupRef = useRef(null);`

I'm registering the plugin the way Camunda tutorials recommend and not the way specified in the link above. Maybe that's the mistake, please let me know if you find something wrong:
`import qosPropertiesProviderModule from './customPropertiesPanel/providers/QualityOfService/qosPropertiesPanelProvider/QosPropertiesProvider';`
`import qosModdleDescriptor from './customPropertiesPanel/descriptors/QosXmlFieldsDescriptor.json';`

`//register custom properties provider`
`const qosPropertiesProviderPlugin = {`
`  __init__: [ 'qosPropertiesProvider' ],`
`  qosPropertiesProvider: [ 'type', qosPropertiesProviderModule ]`
`};`
`registerBpmnJSPlugin(qosPropertiesProviderPlugin);`

`//register descriptor`
`registerBpmnJSModdleExtension(qosModdleDescriptor);`

### Describe the solution you'd like

Update the link above to include special steps to reproduce the example in Camunda Modeler. Also, in a short time, I'd appreciate it if you could please give me some hints on the error I'm facing so this example can work in Camunda Modeler. 

### Additional context

https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-list-extension

**Comment by nikku** [comment]
Do you build your Camunda Modeler plug-in off an extensio? You'd want to use [camunda-modeler-webpack-plugin](https://github.com/camunda/camunda-modeler-webpack-plugin) to perform some internal re-writing and de-duplication of preact.
