### ISSUE TITLE
More complex extensions

### ISSUE THREAD

**Issue by Kylex87** [bpmn-io/bpmn-js-examples#23]
Hi,

great work on providing a mechanism to extend the properties already! 
Since extending the server side trough a ProcessEnginePlugin with a CustomBPMNParseListener is an easy way to extend camunda with more company specific details I think this is a perfect step forward to also include a mechanism on the frontend to edit these company details.

So I tried to adjust the example and add a more complex customization on top of camunda:extensionElements since that sounds like it should be go-to extension point. As far as I can tell from the examples in the moddle-project, I'd need a custom element that is a subclass from 'Element' in order to be part of extensionElements. My first step was to modify the moddle as such:
```
{
  "name": "my-company",
  "prefix": "my",
  "uri": "http://my-company",
  "xml": {
    "tagAlias": "lowerCase"
  },
  "associations": [],
  "types": [
    {
      "name": "MyCompanyDetails",
      superClass: [
      	"Element"
      ],
      properties: [
      {
      	"name": "myFirstAttr",
      	"isAttr": true,
      	"type": "String"
      },
      {
      	"name": "mySecondAttr",
      	"isAttr": true,
      	"type": "Boolean"
      },
      {
      	"name": "myListProp",
      	"isMany": true,
      	"type": "MyListElement"
      }
      ]
    },
    {
   	  "name": "MyListElement",
   	  "properties": [
   	  {
   	  	"name": "text",
   	  	"isAttr": true,
   	  	"type": "String"
   	  },
   	  {
   	  	"name": "value",
   	  	"isBody": true,
   	  	"type": "String"
   	  }
   	  ]
    }
  ]
}
```
Then i tried to link it via the modelProperty as seen in the spell example:
   ```
 group.entries.push(entryFactory.textField({
      id : 'myFistAttr',
      description : 'The first attribute.',
      label : 'First attribute',
      modelProperty : 'myFirstAttr'
    }));
    group.entries.push(entryFactory.checkbox({
        id : 'mySecondAttr',
        description : 'The second attribute.',
        label : 'Second attribute.',
        modelProperty : 'mySecondAttr'
    }));
//    no clue right now how to go forward with customListElement
//    group.entries.push(entryFactory.customListElement({ 
//        id : 'myListProp',
//        description : 'List Property with multiple entries.',
//        label : 'The list for MyListElement.',
//        modelProperty : 'myListProp'
//    }));
```
But that doesn't work anymore for the simple attributes. The error is: 'Error: no namespace uri given for prefix <undefined>'. Is it because I didn't nest it inside of the extensionElement manually but it expects that now, since it's subclassed from Element? 
I tried to use ExtensionElementsHelper to solve that but got stuck pretty since I don't have a general overview on how things should fit together yet. 

So I'm wondering if you'd consider to add a more complex example on how to extend the properties panel with custom tags in general?
If a full example doesn't fit the schedule right now, can you give me some general pointers on which parts I should put my focus on to implement custom nested tags inside of extensionElement? Once I'm done, I'll make sure to provide the example!

**Comment by pedesen** [comment]
Hi,

are you able to provide the complete code of your customization? It would make it a lot easier for us to track down problems.

**Comment by nikku** [comment]
We will close this ticket due to inactivity. Feel free to provide the source code of what you tried and we are happy to help you.
