### ISSUE TITLE
Properties-panel-extension example

### ISSUE THREAD

**Issue by Ixl123** [bpmn-io/bpmn-js-examples#24]
Hi,

is there a way of adding several propertiesProvider and load them? 

example:

index.js files for two provider 

```
module.exports = {
  __init__: [ 'propertiesProvider' ],
  propertiesProvider: [ 'type', require('./ElitePropertiesProvider') ]
};
```

```
module.exports = {
  __init__: [ 'propertiesProvider' ],
  propertiesProvider: [ 'type', require('./MagicPropertiesProvider')]
};
```

now I want to load both providers in the index.js of the app file, which is obviously not working since I just overwrite the first one with the second on.

```
var propertiesPanelModule = require('bpmn-js-properties-panel'),
    propertiesProviderModule = require('./provider/magic'),
    eliteProviderModule = require('./provider/1337'),
    magicModdleDescriptor = require('./descriptors/magic'),
    eliteModdleDescriptor = require('./descriptors/elite');

var container = $('#js-drop-zone');

var canvas = $('#js-canvas');

var bpmnModeler = new BpmnModeler({
  container: canvas,
  propertiesPanel: {
    parent: '#js-properties-panel'
  },
  additionalModules: [
    propertiesPanelModule,
    propertiesProviderModule,
    eliteProviderModule
  ],
  moddleExtensions: {
    magic: magicModdleDescriptor,
    elite: eliteModdleDescriptor
  }
});
```

**Comment by nikku** [comment]
Multiple properties providers are not possible at the moment.

The solution is to sub-class a properties provider or quickly roll your own.

**Comment by Ixl123** [comment]
I cannot get it to run could you provide an example?

What I tried:

1. created two providers
2. one provider inherits from PropertiesActivator
3. the second one is the main provider which inherits from the first one.

Finally I have added the main provider to the additional modules.

**Comment by nikku** [comment]
So the point I wanted to make is that you can only create _one_ provider. Only one is supported and providing more than one will make the second override the first.

If you have customizations you need to create a single provider that defines all tabs, groups, ...
