### ISSUE TITLE
How to disable the zoom in zoom out

### ISSUE THREAD

**Issue by nhatle** [bpmn-io/bpmn-js-examples#26]
Hi,

I have an issue when scroll up and down the diagram by scroll ball on my mouse, it's zoom in / zoom out even if i don't want to, I just want to scroll. 

can you show me how to disable the zoom functionality? 
thanks

**Comment by vkatushenok** [comment]
You can scroll the diagram instead of zooming by pressing `shift` or `ctrl`/`alt`.
