### ISSUE TITLE
An error occurred using Viewer: No Provider for "commandStack"

### ISSUE THREAD

**Issue by yuanxu-xsmy** [bpmn-io/bpmn-js-examples#265]
### Describe the Bug

import Viewer from 'bpmn-js/lib/Viewer'

  import 'bpmn-js/dist/assets/bpmn-js.css'
  import 'bpmn-js/dist/assets/diagram-js.css'
  import 'bpmn-js/dist/assets/bpmn-font/css/bpmn.css'
  const bpmnViewer = new Viewer({
          container: "#canvas",
          keyboard: {bindTo: window},
          propertiesPanel: {
            parent: '#js-properties-panel'
          },
        })
### Steps to Reproduce

![image](https://github.com/bpmn-io/bpmn-js-examples/assets/76983819/c62b07ec-0792-4f73-b7e2-e3b2814e7c25)

1. do this
2. do that
3. now this happens

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
The `keyboard` is a modeler module. What do you expect from using it in the `Viewer` distribution?

**Comment by yuanxu-xsmy** [comment]
Thank you for the reminder. I have commented out this line of code. How can I solve this error?

**Comment by yuanxu-xsmy** [comment]
Thank you for the reminder.
