### ISSUE TITLE
Grunt tasks to re-browserfiy app.js files

### ISSUE THREAD

**Issue by arashTaher** [bpmn-io/bpmn-js-examples#27]
I have a few problems running examples:

First and foremost when I change `app.js`, I want to see the changes immediately, but with current Grunt tasks I have to stop `grunt auto-build`, execute `grunt` to browserify and execute auto-build again.
To overcome this issue I've added `browserify:app` to list of watch tasks. First of all, do you have the same problem or not ? and if so, since I'm not a grunt expert, is my solution correct or not ?

Beside this problem I also encounter `GET http://localhost:9014/livereload.js?snipver=1 net::ERR_EMPTY_RESPONSE` error if I don't start livereload manually. Should I have to do it ? Or am I missing something ?

**Comment by vkatushenok** [comment]
Hi, thank you for reporting this.

Once changes are merged, please pull and `npm install`.

Livereload should work then for all related examples.
