### ISSUE TITLE
Fast usage misupdate nodes properties

### ISSUE THREAD

**Issue by romero83** [bpmn-io/bpmn-js-examples#28]
Hi!

If user clicks fast enough (less than 1 second) on the canvas (which is the process) when typing a property of a node (e.g. start event) then properties-panel updating process' property instead of the start event property.

**Comment by nikku** [comment]
What is it crashing with? Could you provide us with a stack trace (try `F12` to open the developer console and inspect the error).

**Comment by romero83** [comment]
Sorry.. Just updated my first comment.

**Comment by nikku** [comment]
What do you expect? The properties panel is always updating the selected node (that is, the one you clicked).

We could abort the update, if the selection changed. That would be a feature.

**Comment by romero83** [comment]
I expect to update that node property what I changed (typed) and not what I clicked afterwards in that 1 second gap.

**Comment by nikku** [comment]
Closing this as won't fix.
