### ISSUE TITLE
simple-bower example: embedding modeler instead of viewer leads to graphical glitches

### ISSUE THREAD

**Issue by var-const** [bpmn-io/bpmn-js-examples#29]
The README file for the simple-bower example implies that switching from viewer to modeler is as simple as modifying the name of the imported .js file. However, the modeler's connections looks very glitchy (bold black lines with huge black dots) and the left-hand panel is not displayed at all without adding the following lines to index.html:

```html
<link rel="stylesheet" href="../bower_components/bpmn-js/dist/assets/diagram-js.css" />
<link rel="stylesheet" href="../bower_components/bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css" />
```

![bpmn-js-simple-bower-glitch](https://cloud.githubusercontent.com/assets/8216808/16715595/a6bf00c2-46b2-11e6-82e8-d3f365e5900c.png)

**Comment by nikku** [comment]
The `README` did not mention a few stylesheets, you need to embed, too. I updated it accordingly.

```html
<!-- necessary stylesheets -->
<link rel="stylesheet" href="bower_components/bpmn-js/dist/assets/diagram-js.css" />
<link rel="stylesheet" href="bower_components/bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css" />

<script src="bower_components/bpmn-js/dist/bpmn-modeler.js"></script>
```
