### ISSUE TITLE
Custom modeler/properties panel component is missing certain features from properties panel

### ISSUE THREAD

**Issue by WillPascucci** [bpmn-io/bpmn-js-examples#31]
Hi, I have been using the custom bower option to create a custom modeler with properties panel and it has been working great except for the properties panel missing some tabs. In the properties panel normal project, the panel has multiple tabs including "Extensions", etc. From the custom component I created, I only get the "General" tab. Thanks for your help!

**Comment by pedesen** [comment]
Hi, could you provide some source code? At least the part where you load the properties-panel as additional module and define a properties provider would be helpful. Thanks!

**Comment by WillPascucci** [comment]
Hi, my apologies for not including it:
Gruntfile:
`'use strict';

module.exports = function(grunt) {

	// project configuration
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),

		browserify: {

			// create customized bower bundle
			bower: {
				files: {
					'dist/bpmn-viewer-custom.js': [ 'index.js' ]
				},
				options: {
					browserifyOptions: {
						standalone: 'BpmnJS',
						// strip unnecessary built-ins
						builtins: [ 'events' ],
						insertGlobalVars: {
							process: function () {
								return 'undefined';
							},
							Buffer: function () {
								return 'undefined';
							}
						}
					}
				}
			}
		}
	});

	grunt.loadNpmTasks('grunt-browserify');

	grunt.registerTask('default', [ 'browserify:bower' ]);
};`

index.js
`// get bpmn-js
var BpmnViewer = require('bpmn-js/lib/Modeler');

// load additional modules
var additionalModules = [
	require('bpmn-js-properties-panel'),
	require('bpmn-js-properties-panel/lib/provider/bpmn')
];

// add additional (default!) modules to bpmn-js
BpmnViewer.prototype._modules = BpmnViewer.prototype._modules.concat(additionalModules);

// export
module.exports = BpmnViewer;`

package.json:
`{
  "name": "bpmn-js-custom-bundle",
  "version": "0.0.0",
  "description": "Create custom bower bundles of bpmn-js",
  "devDependencies": {
    "grunt": "^0.4.4",
    "grunt-browserify": "^3.3.0"
  },
  "dependencies": {
    "bpmn-js": "^0.15.0",
    "diagram-js": "^0.15.0",
    "bpmn-js-properties-panel": "^0.9.0"
  }
}
`

**Comment by pedesen** [comment]
Hi, in order to edit all properties (bpmn and camunda specific ones) it is necessary to
1. require camunda properties provider and
2. include camunda moddle descriptor

index.js
```javascript
var BpmnViewer = require('bpmn-js/lib/Modeler');

var camundaModdleDescriptor = require('camunda-bpmn-moddle/resources/camunda');

var additionalModules = [
  require('bpmn-js-properties-panel'),

  // 1. require camunda provider instead of the bpmn one (!)
  require('bpmn-js-properties-panel/lib/provider/camunda')
];

BpmnViewer.prototype._modules = BpmnViewer.prototype._modules.concat(additionalModules);

// 2. include camunda moddle descriptor
BpmnViewer.prototype._moddleExtensions = { camunda: camundaModdleDescriptor }

module.exports = BpmnViewer;
```

Furthermore you have to add `camunda-bpmn-moddle` as a dependency to `package.json` to be able to write and read camunda specific properties :

```json
...
  "dependencies": {
    "bpmn-js": "^0.15.0",
    "bpmn-js-properties-panel": "^0.9.0",
    "camunda-bpmn-moddle": "^0.8.1",
    "diagram-js": "^0.15.0"
  }
...
```
