### ISSUE TITLE
not able to "compile" custom-bower-bundle

### ISSUE THREAD

**Issue by bilogic** [bpmn-io/bpmn-js-examples#33]
Hi,

i'm trying to get a web based bpmn page simliar to http://demo.bpmn.io but with properties panel added.
not unfamiliar with npm, nodejs, grunt etc, so just using pure javascript and html.

thus, trying to make a bunch of javascript like https://github.com/bpmn-io/bpmn-js-seed
managed to get a single ```bundle.js``` using browsify, but that is 1 big ```.js``` file, different from ```bpmn-js-seed```, which are many ```.js``` files in a ```dist``` folder.

my steps are as follows:

1. cloned this repository using ```git```
2. changed folder to ```/bpmn-js/examples/custom-bower-bundle```
3. executed ```npm install```, many errors logged in ```npm-debug.log```
[npm-debug.log.txt](https://github.com/bpmn-io/bpmn-js-examples/files/682482/npm-debug.log.txt)

any help is greatly appreciated!

**Comment by nikku** [comment]
Quoting the relevant pieces from the log file you attached:

```
1127 error Error: ENOENT, utime '/var/www/html/bpmn-js-examples/custom-bower-bundle/node_modules/grunt/node_modules/async/.gitmodules'
1128 error If you need help, you may report this log at:
1128 error     <http://github.com/isaacs/npm/issues>
1128 error or email it to:
1128 error     <npm-@googlegroups.com>
1129 error System Linux 2.6.32-431.23.3.el6.x86_64
1130 error command "node" "/usr/bin/npm" "install"
1131 error cwd /var/www/html/bpmn-js-examples/custom-bower-bundle
1132 error node -v v0.10.48
1133 error npm -v 1.3.6
1134 error path /var/www/html/bpmn-js-examples/custom-bower-bundle/node_modules/grunt/node_modules/async/.gitmodules
1135 error fstream_path /var/www/html/bpmn-js-examples/custom-bower-bundle/node_modules/grunt/node_modules/async/.gitmodules
```

This seems like it is an error fetching the `async` module, used by `grunt`. 

You use a _very_ old version of NodeJS (0.10.0). Try if updating to something stable (i.e. 4.0.0) helps. There is nothing we can do to fix about this.

**Comment by bilogic** [comment]
Thanks! do you mind giving a hint on how to upgrade NodeJS? I have been struggling for hours and have was not able to decode the logs until you helped

**Comment by bilogic** [comment]
I managed to update ```NodeJS``` to v6.9.2!
