### ISSUE TITLE
Error when running `grunt auto-build`

### ISSUE THREAD

**Issue by bilogic** [bpmn-io/bpmn-js-examples#34]
Hi,

I used ```grunt build``` successfully on the ```bpmn-js-properties-panel``` example.
However, ```grunt auto-build``` results in an error ```UnhandledPromiseRejectionWarning``` each time it is executed. When the files in ```app``` are edited and saved, the example turns back to just a normal modeler without the properties panel.

Any idea what might be causing the problem? Thank you.

```
Running "browserify:watch" (browserify) task
>> Bundle dist/index.js created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9013

Running "watch" task
Waiting...
(node:4384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
```

**Comment by bilogic** [comment]
Hi,

When running ```grunt auto-build```, my expectation is for the files in ```dist``` to rebuild themselves whenever the sources are updated. However, based on timestamps, ```index.js``` is not being rebuilt. Is this by design?

**Comment by bilogic** [comment]
Hi,

Just to note, ```grunt build``` also takes extremely long (~60 seconds) to complete, with the bulk of the wait taken by ```browserify:app```. When running ```grunt auto-build```, ```browserify:watch``` also takes a similar amount of time.

My ```node``` and ```npm``` versions as follows:

```
[properties-panel]# node -v
v6.9.2
[properties-panel]# npm -v
3.10.9
```

Any help is greatly appreciated! Thank you.

**Comment by philippfromme** [comment]
I can't reproduce those errors. Can you please check if the errors still occur in the current version of the example?

**Comment by tianxiaofeng747** [comment]
When running grunt  , i see error  
it's message  
`Running "browserify:app" (browserify) task
>> Error: Cannot find module '../../../../.1.1.5@is-buffer/index.js' from 'E:\work\web-bpmn\bpmn-js-examples\properties-panel\node_modules\.1.0.2@core-util-is\lib'`
my node version is 8.4.0

**Comment by nikku** [comment]
This seems to be releated to individual NODE / npm setups.

**Comment by chris-aeviator** [comment]
I was able to get rid of this error by setting `connect.livereload.options.open=false` inside `Gruntfile.js`
