### ISSUE TITLE
properties-panel-extension doc issue

### ISSUE THREAD

**Issue by felixlinker** [bpmn-io/bpmn-js-examples#35]
In the code example [Define a group](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension#define-a-group) in the `properties-panel-extension` folder, there is writte that `spellProps` should be invoked in the field `entries` of `blackMagicGroup`. That doesn't make any sense since this function doesn't return anything. In you [code example](https://github.com/bpmn-io/bpmn-js-examples/blob/master/properties-panel-extension/app/provider/magic/MagicPropertiesProvider.js#L64) you don't invoke the function.

This lead to much confusion for me, I think your `README.md` is wrong at this point.

**Comment by felixlinker** [comment]
Isseu fixed here: https://github.com/bpmn-io/bpmn-js-examples/pull/37

**Comment by pedesen** [comment]
Updated the example docs via https://github.com/bpmn-io/bpmn-js-examples/commit/887a64257291592ce2bc869f231fab263a42b3be. See [forum thread](https://forum.bpmn.io/t/properties-panel-extension-descriptor/1397/5).
