### ISSUE TITLE
issue adding custom elements to bpmn io xml file

### ISSUE THREAD

**Issue by rohitbajaniya** [bpmn-io/bpmn-js-examples#36]
custom elements are not getting added to the XML

**Comment by nikku** [comment]
Please provide concrete steps that allow us to reproduce your issue.

**Comment by rohitbajaniya** [comment]
Use this example (https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements)
how to download custom elements in xml? I have try to added download link but downloaded only bpmn element custom elements are missing in xml file.

**Comment by nikku** [comment]
Yes, that is because custom elements are available via `customModeler.getCustomElements();`.

You could build you own way to somehow serialize them in XML, this is out of scope of the example though.

**Comment by rohitbajaniya** [comment]
Can you provide example **custom elements + xml download** ?

**Comment by nikku** [comment]
You cannot easily download custom elements as part of XML, because they may not be necessarily BPMN 2.0 compliant.

So no, we cannot provide a generic example for that. If you provide us pointers on your use-case we may be able to help you out though.
