### ISSUE TITLE
grunt auto-build  ERROR

### ISSUE THREAD

**Issue by winson2work** [bpmn-io/bpmn-js-examples#42]
grunt auto-build
Running "copy:diagram_js" (copy) task
Copied 1 file

Running "copy:bpmn_js" (copy) task
Copied 6 files

Running "copy:app" (copy) task
Copied 2 files

Running "less:styles" (less) task
>> 1 stylesheet created.

Running "browserify:watch" (browserify) task
>> Error: Cannot find module '../../../../_is-buffer@1.1.5@is-buffer/index.js' from 'D:\projects\properties-panel\node_modules\_core-util-is@1.0.2@core-util-is\lib'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

---  npm@3.10.10

**Comment by winson2work** [comment]
answer

**Comment by philippfromme** [comment]
Can you please give some more context? Is this the properties-panel example? What are the steps to reproduce this?

**Comment by winson2work** [comment]
have already been solved 。 ths.

**Comment by VGerris** [comment]
hi,

Can you tell how this was resolved? I have the exact same problem when I try to run grunt in the properties example with bpmn-js included locally instead via npm. The build from bpmn.js git repo is not the same as the one via npm. Why is that?

**Comment by nikku** [comment]
> The build from bpmn.js git repo is not the same as the one via npm. Why is that?

What exactly do you do?

**Comment by nikku** [comment]
This is a limitation of `npm link`. You must install the dependency in your local `bpmn-js`.

**Comment by VGerris** [comment]
Can you be more specific? I did an npm install in both directories. I have the same issue using the bundle example.

**Comment by nikku** [comment]
```
cd bpmn-js
npm install --save-dev babel-preset-env
npm link

cd example
npm link bpmn-js
```

**Comment by VGerris** [comment]
Thanks, works like a charm :). Perhaps good to note that somewhere in the dev setup guide? I'm new to this stack and I wasn't able to figure this out easily. Thank you for the help and quick response.
