### ISSUE TITLE
What is the difference between 'extends' and 'superClass' ?

### ISSUE THREAD

**Issue by guilmori** [bpmn-io/bpmn-js-examples#44]
Looking at the properties-panel-extension example:
https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension

In the Moddle descriptor file, what is the difference between 'extends' vs 'superClass' ?

I see 'superClass' being used when looking at default BPMN Moddle here:
https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json

**Comment by nikku** [comment]
Cf. https://github.com/bpmn-io/moddle/blob/master/docs/descriptor.md#extending-existing-types.
