### ISSUE TITLE
How to open an old BPMN diagram for edit functionality?

### ISSUE THREAD

**Issue by Zalasanjay** [bpmn-io/bpmn-js-examples#45]
i want to open my previously saved diagram 
so, is it possible? if yes please guide me....

Thank You.

**Comment by philippfromme** [comment]
Which example are you refering to?

**Comment by Zalasanjay** [comment]
@philippfromme "Properties Panel Extension Example"

**Comment by Zalasanjay** [comment]
@philippfromme can you please say me that editing in previously saved BPMN diagram is possible or not?

**Comment by philippfromme** [comment]
You can always import a diagram when using bpmn-js. Use [importXML](https://github.com/bpmn-io/bpmn-js/blob/master/lib/Viewer.js#L149) for that.

**Comment by Zalasanjay** [comment]
@philippfromme thanks...
