### ISSUE TITLE
what is this :   "emumerations": [ ],   "associations": [ ]

### ISSUE THREAD

**Issue by samanspd** [bpmn-io/bpmn-js-examples#47]
"emumerations": [ ],   "associations": [ ]
use for?
 and what is this

**Comment by philippfromme** [comment]
Which example are you refering to?

**Comment by samanspd** [comment]
i have address page  this is:
https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-meta-model/resources/qa.json

**Comment by samanspd** [comment]
i am refer to this file in address

**Comment by nikku** [comment]
Closing this in favor of https://github.com/bpmn-io/moddle/issues/20.
