### ISSUE TITLE
tiny-svg@0.3.0 dependency in  custom-elements 

### ISSUE THREAD

**Issue by JonasHodel** [bpmn-io/bpmn-js-examples#50]
In the custom element example npm will install the version @0.3.0 from the tiny-svg package. However the current package version is @0.1.3. As a result of that the packages cannot be installed. 

https://github.com/bpmn-io/tiny-svg/releases

https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/package.json

**Comment by nikku** [comment]
Thanks for reporting.

**Comment by JonasHodel** [comment]
I tried the example again. The npm install does now work but after the grunt build I get an Error in the Application because the Function registerProvider on the contextpad does not exists. Could it be that there are further bugs in this example?
