### ISSUE TITLE
Use bpmn:SequenceFlow for custom element

### ISSUE THREAD

**Issue by minhquankq** [bpmn-io/bpmn-js-examples#53]
I want to use `bpmn:SequenceFlow` for custom element by `return {type: 'custom:connection'}` in function `canConnect` in file `CustomRules.js`
However, the sequence flow was removed when moving element.
Detail: see attachment
![peek 2018-03-16 16-38_2](https://user-images.githubusercontent.com/18256815/37515985-4f33b03e-293f-11e8-8311-efb714caab8f.gif)
 Could you please help.

**Comment by nikku** [comment]
The modeler validates rules whenever stuff happens on the diagram.

In your particular case the modeling rules check, whether the element (circle) can still be connected to the task via a sequence flow. The answer appears to be no.
