### ISSUE TITLE
How to integrate BPMN -js in vue?

### ISSUE THREAD

**Issue by 1012620005** [bpmn-io/bpmn-js-examples#54]
How to integrate BPMN -js in vue?

**Comment by philippfromme** [comment]
The right place to ask questions is the [bpmn.io forum](https://forum.bpmn.io/).

**Comment by nikku** [comment]
I've created [vue-bpmn](https://github.com/bpmn-io/vue-bpmn), a library that displays BPMN 2.0 diagrams inside a Vue.js application.

It ships with [an example](https://github.com/bpmn-io/vue-bpmn/tree/master/example) as well as [a basic implementation](https://github.com/bpmn-io/vue-bpmn/blob/master/src/index.vue) that shows how an integration could look like.
