### ISSUE TITLE
Custom elements example not working

### ISSUE THREAD

**Issue by siffogh** [bpmn-io/bpmn-js-examples#57]
I followed the documentation in the [custom elements example]() but I am unable to see the expected results. I get the following error:

<img width="604" alt="screen shot 2018-05-30 at 13 56 05" src="https://user-images.githubusercontent.com/4761023/40718681-40dd2530-6411-11e8-8a36-664c17abb97c.png">

Am I supposed to do anything in particular other than the steps specified in the docs? (npm install and npm run dev)

**Comment by nikku** [comment]
Did you clean your `node_modules` folder before? I cannot reproduce the issues your seeing.

**Comment by siffogh** [comment]
My bpmn-js module was linked locally. Therefore, I am closing the issue.
