### ISSUE TITLE
add Property to bpmn process. The version Tag!

### ISSUE THREAD

**Issue by Diaskhan** [bpmn-io/bpmn-js-examples#62]
add Property to bpmn process.
Its posssible to add property that they binded in process or definition TAG ??
see a and example !
I need to add version tag to bpmn file version="2017.8.31" it possible to doit for definition or process tag ?
Every bpmn process have a version !

https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-meta-model

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   id="ErrorHandling" VERSION="2017.8.31">
  <bpmn2:process id="Process_1"  VERSION="2017.8.31">
  </bpmn2:process>
</bpmn2:definitions>
```

**Comment by nikku** [comment]
If you're using `camunda` there exists a [`camunda:versionTag`](https://docs.camunda.org/manual/7.9/reference/bpmn20/custom-extensions/extension-attributes/#versiontag) property.

**Comment by Diaskhan** [comment]
ok how then add it to property panel ?
