### ISSUE TITLE
bpmn-js/examples/colors bug - menu doesn't open.

### ISSUE THREAD

**Issue by pihh** [bpmn-io/bpmn-js-examples#64]
NOTE: this bug is related to the [bpmn-js-in-color package](https://github.com/bpmn-io/bpmn-js-in-color) but since I wasn't able to open the issue there I decided to report this here. 

Running your example throws an error. It says _popupMenu.create is undefined.

I managed to solve this proble by going to the file ColorContextPadProvider.js ,  on the method getContextPadEntries , at actions -> action -> click  

and replace the your code with :

```
          self._popupMenu.close();

          var opts = getStartPosition(self._canvas, self._contextPad, element);

          // or fallback to current cursor position
          opts.cursor = {
            x: event.x,
            y: event.y
          };

          self._popupMenu.open(element,'color-picker',opts);
```

I'm not familiar with this library, it's the second day I'm working with it, so it probably its not the best fix in the world but I think that this is a awesome piece of software and I decided to give my 2 cents to improve it ( and if possible remove workload from your shoulders ).

Kind regards, 

Filipe Sá - Expert Software Developer @ IBM - SoftINSA

**Comment by nikku** [comment]
The library requires a peer dependency of `bpmn-js@0.x` to work.

I assume you're a more recent version of the library where we [refactored the popup menu API](https://github.com/bpmn-io/diagram-js/blob/master/CHANGELOG.md#200).

**Comment by nikku** [comment]
If you'd like to contribute consider a PR that updates the example to the latest version.
