### ISSUE TITLE
Custom element to palette

### ISSUE THREAD

**Issue by mytran22** [bpmn-io/bpmn-js-examples#70]
I need to add custom elements to the palette. So I can assign custom behaviour when uses that item.
That project makes it but as a new module: https://github.com/bpmn-io/bpmn-js-nyan

Is it possible to customize palette (for example adding a new button) with the custom behaviour (for example writing something to console) and add this in to the "bpmn-js-examples/custom-elements/" ?

**Comment by barmac** [comment]
The example you are asking for is already available here: https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/custom/CustomPalette.js

If it is not what you are looking for, please explain that in a more verbose way.

**Comment by trante** [comment]
As far as I see CustomPalette.js is only included in this file: https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/custom/index.js

It would be helpful if it was used in an example so I can see how can I include and make it work.

**Comment by mytran22** [comment]
As far as I see CustomPalette.js is only included in this file: https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/custom/index.js

It would be helpful if it was used in an example so I can see how can I include and make it work.

**Comment by barmac** [comment]
If you do not want to use a custom modeler, you can still provide custom palette as an additional module. See this for guidance: https://github.com/bpmn-io/bpmn-js/blob/master/lib/Modeler.js#L60
