### ISSUE TITLE
Migrate static examples away from rawgit

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-examples#76]
Context: Rawgit (our current asset provider) is shutting down. Cf. https://rawgit.com.

**Comment by pinussilvestrus** [comment]
The link for #74 pr seems to be broken.

**Comment by nikku** [comment]
It seems like the PR got deleted. Linked the actual source.

**Comment by pinussilvestrus** [comment]
## Alternatives

tba

according to `RawGit`:

- jsDelivr
- GitHub Pages
- CodeSandbox
- unpkg

## Effected examples

- [`colors`](https://github.com/bpmn-io/bpmn-js-examples/tree/master/colors)
    - [file storage](https://github.com/bpmn-io/bpmn-js-examples/blob/master/colors/index.html#L94)
    - [try out](https://github.com/bpmn-io/bpmn-js-examples/blob/master/colors/README.md)
- [`starter`](https://github.com/bpmn-io/bpmn-js-examples/tree/master/starter)
   - [file storage](https://github.com/bpmn-io/bpmn-js-examples/blob/master/starter/modeler.html) (also inside viewer)
   - [try out](https://github.com/bpmn-io/bpmn-js-examples/blob/master/starter/README.md)
- [`url-viewer`](https://github.com/bpmn-io/bpmn-js-examples/blob/master/url-viewer/)
   - [file storage](https://github.com/bpmn-io/bpmn-js-examples/blob/master/url-viewer/index.html#L35)
   - [try out](https://github.com/bpmn-io/bpmn-js-examples/blob/master/url-viewer/README.md)
- [`pre-packaged`](https://github.com/bpmn-io/bpmn-js-examples/blob/master/pre-packaged/README.md)
- [`interaction`](https://github.com/bpmn-io/bpmn-js-examples/blob/master/interaction/README.md)
- [`custom-bundle`](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-bundle/)
   - [file storage](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-bundle/index.html#L43)

**Comment by pinussilvestrus** [comment]
I'd personally go for `jsDelivr`. Any opinions? @barmac @philippfromme @nikku ?

**Comment by barmac** [comment]
Sounds good to me.

**Comment by nikku** [comment]
> I'd personally go for jsDelivr.

How did you choose it? Does it allow us to serve HTML files ([cf. example](https://rawgit.com/bpmn-io/bpmn-js-examples/master/starter/viewer.html))?

**Comment by pinussilvestrus** [comment]
First thought so, but it reveals it does not offer it, just static cdn ⛔️... will check for another option

**Comment by nikku** [comment]
Statically looks like a good solution.

**Comment by nikku** [comment]
For reference, [here are usages of rawgit](https://github.com/search?q=org%3Abpmn-io+rawgit&type=Code) in our code base.

**Comment by pinussilvestrus** [comment]
Closed via 5960606
