### ISSUE TITLE
Add a Vue integration example

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-examples#79]
Related to https://github.com/bpmn-io/bpmn-js-examples/issues/54 and [forum questions](https://forum.bpmn.io/t/bpmn-js-with-vue/2608/4) we should create an example how to integrate bpmn-js with Vue.

**Comment by qtttttttttting** [comment]
wait for the example too

**Comment by nikku** [comment]
I've created [vue-bpmn](https://github.com/bpmn-io/vue-bpmn), a library that displays BPMN 2.0 diagrams inside a Vue.js application.

It ships with [an example](https://github.com/bpmn-io/vue-bpmn/tree/master/example) as well as [a basic implementation](https://github.com/bpmn-io/vue-bpmn/blob/master/src/index.vue) that shows how an integration could look like.
