### ISSUE TITLE
Custom Button on the right-side of a shape already in place.

### ISSUE THREAD

**Issue by ramonck** [bpmn-io/bpmn-js-examples#8]
So I wanted to do a custom overlay in a shape already available, how could I add like a custom button on the right-side of the shape for an action to be taken?

Didn't find that in the examples, sorry if it's too obvious but I didn't see it.

Best Regards,

**Comment by nikku** [comment]
You should be able to add a custom button as [an overlay](https://github.com/bpmn-io/bpmn-js-examples/tree/master/overlays) to the diagram. I added a [note](https://github.com/bpmn-io/bpmn-js-examples/blob/master/overlays/README.md#interacting-with-overlays) to the overlays example showcasing this use case.
