### ISSUE TITLE
Refactor Custom Elements Example

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-examples#80]
# Current Status

We currently have three examples related to custominzing elements:

* [Custom Meta Model](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-meta-mode) - An example of adding custom properties to existing elements while maintaining BPMN 2.0 compatibility.
* [Nyan Cat](https://github.com/bpmn-io/bpmn-js-nyan) - An example of rendering an existing element (bpmn:ServiceTask) differently.
* [Custom Elements](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements) - An example of adding custom elements while maintaining BPMN 2.0 compatibility.

There's a lot of confusion when it comes to custom elements. Most people would probably want custom properties and render an element that has custom properties differently like in this example:

* [Custom Elements](https://github.com/philippfromme/bpmn-js-custom-elements-example) - An example of adding custom properties to existing elements and rendering them differently while maintaining BPMN 2.0 compatibility.

# Improvements

We should provide better guidance for people interested in customizing elements. Therefore we should:

* have all examples regarding the customization of elements in seperate repositories
* have a single README in this repository listing different ways of customizing elements that people can use as a starting point
* link back to this README from each repository so people are aware that there are different ways of customizing elements

**Comment by nikku** [comment]
Related to https://github.com/bpmn-io/bpmn-js/issues/711.

**Comment by philippfromme** [comment]
For the reviewer:

* https://github.com/bpmn-io/bpmn-js-examples - __README has been updated__
* https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements - __Example has been moved to seperate repository, new README gives an introduction to custom elements__
* https://github.com/bpmn-io/bpmn-js-example-model-extension - __New example of creating a model extension__
* https://github.com/bpmn-io/bpmn-js-example-custom-rendering - __New example of creating custom rendering__
* https://github.com/bpmn-io/bpmn-js-example-custom-controls - __New example of creating custom controls__
* https://github.com/bpmn-io/bpmn-js-example-custom-elements - __Example has been refactored to align with previous examples__
* https://github.com/bpmn-io/bpmn-js-nyan - __README has been updated to include hint about custom elements__

**Comment by nikku** [comment]
:cake:
