### ISSUE TITLE
How to inherits element?

### ISSUE THREAD

**Issue by dangviettuan** [bpmn-io/bpmn-js-examples#83]
Can we create an custom element which inherit from an existed element. For example can I create an MyElement which inherit ServiceTask.

**Comment by philippfromme** [comment]
Yes, you can. Please head over to our forum for anything that is not a bug/feature request. This is a very common question and has been asked many times.

**Comment by dangviettuan** [comment]
Thanks a lot.

**Comment by cdarbha** [comment]
Hello Philip

I am from the same team as Tuan and we did implement custom elements. 

To give a background to what we are trying to achieve, we are trying to build a custom modeler toolbox which encompasses certain default functionality specific to an industry domain. We are extending Service Task and User Tasks to achieve our functionality. When we did custom elements (nsx:CustomTask) it was all good but when we deployed to Camunda it rejected saying that it doesnt understand our nsx:CustomTask. 

We explored further and realized Camunda needs to be extended to make this work. Hence we switched to element templates, but this gets appliedTo the default servicetask as well and it gets complicated when we have multiple such extended ServiceTask or UserTasks.

We need your help to get this working. 

Thanks in Advance
Chandra

**Comment by nikku** [comment]
In essence, you must make sure that the resulting XML is still BPMN 2.0. Without doing so you end up in the situation you described: 

> When we did custom elements (nsx:CustomTask) it was all good but when we deployed to Camunda it rejected saying that it doesnt understand our nsx:CustomTask.

@philippfromme posted an example that sketches how you guys need to proceed: The [bpmn-js-custom-elements-example](https://github.com/bpmn-io/bpmn-js-custom-elements-example) shows how to create custom elements while staying BPMN 2.0 compliant. Try out the example and give us feedback whether it works for you.

> To give a background to what we are trying to achieve, we are trying to build a custom modeler toolbox which encompasses certain default functionality specific to an industry domain. We are extending Service Task and User Tasks to achieve our functionality. 

This use case should be 100% covered by the example. Try it out.

**Comment by cdarbha** [comment]
Thanks @nikku! We tried it earlier but will give it a shot once again. Just one point. Do we have a working example which generates Custom BPMN XML which can be deployed into Camunda? Below is an example bpmn XML which we generated using the Custom Elements. 

Sorry if I am asking a basic question, but does the bpmn below look compliant to bpmn 2.0?

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:hpi="http://www.hcc.com/hpi" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_1" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1" />
    <hpi:materialTask id="MaterialTask_0pkz8e3"> <!-- This one -->
      <bpmn2:extensionElements>
        <camunda:properties>
          <camunda:property />
        </camunda:properties>
      </bpmn2:extensionElements>
    </hpi:materialTask>
    <bpmn2:serviceTask id="Task_15gxk94" camunda:class="" />
    <hpi:modbusTask id="ModbusTask_1vdoa3w" camunda:class="com.hcc.hpi.toolbox.modbus.ModbusServiceTask" /> <!-- This line -->
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="412" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="MaterialTask_0pkz8e3_di" bpmnElement="MaterialTask_0pkz8e3">
        <dc:Bounds x="591" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ServiceTask_1huc8w2_di" bpmnElement="Task_15gxk94">
        <dc:Bounds x="358" y="442" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ModbusTask_1vdoa3w_di" bpmnElement="ModbusTask_1vdoa3w">
        <dc:Bounds x="653" y="453" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>

```
