### ISSUE TITLE
bpmn-js Modeler, overlays.add method throwing runtime error: invalid element specified

### ISSUE THREAD

**Issue by PragyanshuShukla** [bpmn-io/bpmn-js-examples#87]
I am saving the imported xml in data base by using modeler bpmnModeler.saveXML. I am using jquery to  save in database. When i am rendering the same xml from database and  using bpmnModeler.importXML. diagram rendered but it is throwing **runtime error: invalid element specified** on overlays.add method.
 I am using https://unpkg.com/bpmn-js@3.1.0/dist/bpmn-modeler.development.js

**Comment by nikku** [comment]
```
runtime error: invalid element specified
```

This error indicates a miss-use of the `Overlays#add` API.

Please provide us with concrete steps to reproduce your issue.

**Comment by PragyanshuShukla** [comment]
Nicku, I used Modeler starter as u suggested. just one change i did that importing the diagram from the xml stored in the database. Please find attached code.



<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>

    
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js@3.1.0/dist/assets/diagram-js.css">
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js@3.1.0/dist/assets/bpmn-font/css/bpmn.css">

    
    <script src="https://unpkg.com/bpmn-js@3.1.0/dist/bpmn-modeler.development.js"></script>

    
    <script src="https://unpkg.com/jquery@3.3.1/dist/jquery.js"></script>

    
    <style>
      html, body, #canvas {
        height: 100%;
        padding: 0;
        margin: 0;
      }

      .diagram-note {
        background-color: rgba(66, 180, 21, 0.7);
        color: White;
        border-radius: 5px;
        font-family: Arial;
        font-size: 12px;
        padding: 5px;
        min-height: 16px;
        width: 50px;
        text-align: center;
      }

      .needs-discussion:not(.djs-connection) .djs-visual > :nth-child(1) {
        stroke: rgba(66, 180, 21, 0.7) !important; /* color elements as red */
      }

      #save-button {
        position: fixed;
        bottom: 20px;
        left: 20px;
      }
    </style>
  </head>
  <body>
    <div id="canvas"></div>

    <button id="save-button">print to console</button>
    
    <script>

      var diagramUrl = 'https://cdn.rawgit.com/bpmn-io/bpmn-js-examples/dfceecba/starter/diagram.bpmn';

      // modeler instance
      var bpmnModeler = new BpmnJS({
        container: '#canvas',
        keyboard: {
          bindTo: window
        }
      });

      /**
       * Save diagram contents and print them to the console.
       */
      function exportDiagram() {

          bpmnModeler.saveXML({ format: true }, function (err, xml) {

              if (err) {
                  return console.error('could not save BPMN 2.0 diagram', err);
              }

              alert('Diagram exported. Check the developer tools!');

            
              SaveDesigneInDB(xml, xml);
             
          });
      }

     
  
    
      function openDiagram(bpmnXML) {


        // import diagram
        bpmnModeler.importXML(bpmnXML, function(err) {
            
            if (err) {
             
                return console.error('could not import BPMN 2.0 diagram', err);
            }
           
          // access modeler components
          var canvas = bpmnModeler.get('canvas');
          var overlays = bpmnModeler.get('overlays');


          // zoom to fit full viewport
          canvas.zoom('fit-viewport');

          // attach an overlay to a node
          overlays.add('SCAN_OK', 'note', {
            position: {
              bottom: 0,
              right: 0
            },
            html: '<div class="diagram-note">Mixed up the labels?</div>'
          });

          // add marker
            canvas.addMarker('SCAN_OK', 'needs-discussion');

            var eventBus = bpmnModeler.get('eventBus');

            // you may hook into any of the following events
            var events = [
                //'element.hover',
                //'element.out',
                //'element.click',
                'element.dblclick',
                //'element.mousedown',
                //'element.mouseup'
            ];

            events.forEach(function (event) {

                eventBus.on(event, function (e) {
                    // e.element = the model element
                    // e.gfx = the graphical element
                    alert(e.element.id);
                    //console.log(event, 'on', e.element.id);
                });
            });

        });
      }


      // load external diagram file via AJAX and open it
        var wfID = 7; // if it is zero then open default diagram as provided in the diagramURL
        if (wfID > 0) {
            var urlGetDiagram = "Server.asmx/GetWorkflow";
            $.get(urlGetDiagram,{ workFlowID: wfID},openDiagram, 'text');
        } else {
            $.get(diagramUrl, openDiagram, 'text');
        }

      // wire save button
        $('#save-button').click(exportDiagram);

        function SaveDesigneInDB(diagram,attributexml) {
            //save digram to database
           
            $.ajax({
                type: "POST",
                url: "Server.asmx/SaveWorkflow",
                contentType: "application/json; charset=utf-8",
                data: "{xmlDiagram:'" +JSON.stringify(diagram) + "',attributeXML:'" + attributexml+"'}",
                dataType: "json",
                success: function (data) {
                    //alert(data);
                    alert(data.d);
                },
                error: TypesFailed
            });
        }

        function TypesFailed(result) {
            alert('Failed: ' + result.responseText);
        }

        function GetWorkflowDiagram() {
            //var diagram = "<Category><categoryId>007</categoryId><categoryName>Ajax</categoryName></Category>";
            $.ajax({
                type: "POST",
                url: "Server.asmx/SaveWorkflowTest",
                dataType: "xml",
                contentType: "application/xml",
                data: "{xmlDiagram':" + diagram + "'}",
                success: function (res) {
                    alert("XML: it works!");
                },
                error: function (res) {
                    
                    alert("XML: not working! " + res.responseText);
                    console.log('error', res.responseText)
                }
            });
        }
    </script>
    
  </body>
</html>


**My xml is** 
<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL http://www.omg.org/spec/BPMN/2.0/20100501/BPMN20.xsd">
  <collaboration id="Collaboration_01e7pxi">
    <participant id="Participant_0qokjmp" processRef="Process_1l83wxo" />
  </collaboration>
  <process id="Process_1l83wxo">
    <startEvent id="StartEvent_12upy1w">
      <outgoing>SequenceFlow_020ayl3</outgoing>
    </startEvent>
    <sequenceFlow id="SequenceFlow_020ayl3" sourceRef="StartEvent_12upy1w" targetRef="Task_18hw8pa" />
    <task id="Task_1fgrp3g">
      <incoming>SequenceFlow_1fln8op</incoming>
    </task>
    <task id="Task_18hw8pa">
      <incoming>SequenceFlow_020ayl3</incoming>
      <outgoing>SequenceFlow_0kunebt</outgoing>
      <outgoing>SequenceFlow_0br1l3p</outgoing>
    </task>
    <exclusiveGateway id="ExclusiveGateway_1jxmreu">
      <incoming>SequenceFlow_0kunebt</incoming>
      <outgoing>SequenceFlow_1fln8op</outgoing>
      <outgoing>SequenceFlow_11c614h</outgoing>
    </exclusiveGateway>
    <sequenceFlow id="SequenceFlow_1fln8op" sourceRef="ExclusiveGateway_1jxmreu" targetRef="Task_1fgrp3g" />
    <sequenceFlow id="SequenceFlow_0kunebt" sourceRef="Task_18hw8pa" targetRef="ExclusiveGateway_1jxmreu" />
    <exclusiveGateway id="ExclusiveGateway_0lqpaye">
      <incoming>SequenceFlow_11c614h</incoming>
    </exclusiveGateway>
    <sequenceFlow id="SequenceFlow_11c614h" sourceRef="ExclusiveGateway_1jxmreu" targetRef="ExclusiveGateway_0lqpaye" />
    <sequenceFlow id="SequenceFlow_0br1l3p" sourceRef="Task_18hw8pa" targetRef="EndEvent_0hzbje2" />
    <endEvent id="EndEvent_0hzbje2">
      <incoming>SequenceFlow_0br1l3p</incoming>
    </endEvent>
  </process>
  <bpmndi:BPMNDiagram id="sid-74620812-92c4-44e5-949c-aa47393d3830">
    <bpmndi:BPMNPlane id="sid-cdcae759-2af7-4a6d-bd02-53f3352a731d" bpmnElement="Collaboration_01e7pxi">
      <bpmndi:BPMNShape id="Participant_0qokjmp_di" bpmnElement="Participant_0qokjmp">
        <omgdc:Bounds x="374" y="97" width="600" height="250" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="StartEvent_12upy1w_di" bpmnElement="StartEvent_12upy1w">
        <omgdc:Bounds x="421" y="133" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_18hw8pa_di" bpmnElement="Task_18hw8pa">
        <omgdc:Bounds x="512" y="128" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_020ayl3_di" bpmnElement="SequenceFlow_020ayl3">
        <omgdi:waypoint x="457" y="151" />
        <omgdi:waypoint x="485" y="151" />
        <omgdi:waypoint x="485" y="168" />
        <omgdi:waypoint x="512" y="168" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Task_1fgrp3g_di" bpmnElement="Task_1fgrp3g">
        <omgdc:Bounds x="718" y="128" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ExclusiveGateway_1jxmreu_di" bpmnElement="ExclusiveGateway_1jxmreu" isMarkerVisible="true">
        <omgdc:Bounds x="631" y="143" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_1fln8op_di" bpmnElement="SequenceFlow_1fln8op">
        <omgdi:waypoint x="681" y="168" />
        <omgdi:waypoint x="718" y="168" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_0kunebt_di" bpmnElement="SequenceFlow_0kunebt">
        <omgdi:waypoint x="612" y="168" />
        <omgdi:waypoint x="631" y="168" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="ExclusiveGateway_0lqpaye_di" bpmnElement="ExclusiveGateway_0lqpaye" isMarkerVisible="true">
        <omgdc:Bounds x="718" y="253" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_11c614h_di" bpmnElement="SequenceFlow_11c614h">
        <omgdi:waypoint x="656" y="193" />
        <omgdi:waypoint x="656" y="278" />
        <omgdi:waypoint x="718" y="278" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_0hzbje2_di" bpmnElement="EndEvent_0hzbje2">
        <omgdc:Bounds x="558" y="272" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0br1l3p_di" bpmnElement="SequenceFlow_0br1l3p">
        <omgdi:waypoint x="562" y="208" />
        <omgdi:waypoint x="562" y="234" />
        <omgdi:waypoint x="576" y="234" />
        <omgdi:waypoint x="576" y="272" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
    <bpmndi:BPMNLabelStyle id="sid-e0502d32-f8d1-41cf-9c4a-cbb49fecf581">
      <omgdc:Font name="Arial" size="11" isBold="false" isItalic="false" isUnderline="false" isStrikeThrough="false" />
    </bpmndi:BPMNLabelStyle>
    <bpmndi:BPMNLabelStyle id="sid-84cb49fd-2f7c-44fb-8950-83c3fa153d3b">
      <omgdc:Font name="Arial" size="12" isBold="false" isItalic="false" isUnderline="false" isStrikeThrough="false" />
    </bpmndi:BPMNLabelStyle>
  </bpmndi:BPMNDiagram>
</definitions>
