### ISSUE TITLE
Custom palette elements at runtime

### ISSUE THREAD

**Issue by kmanikandanmca2008** [bpmn-io/bpmn-js-examples#88]
Hi ,
I have a requirement like building our own palette elements and play around like search palette elements, add , remove and filter elements at runtime based on user inputs. For this , I have seen the custom palette example but i didnt find a way to do stuff at runtime manipulations.

I need to do showing and hiding of default elements and custom elements like basic palette and advanced palette.These two type i want to build using bpmn js

**Comment by nikku** [comment]
The [`Palette`](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/palette/Palette.js) has an internal `_update` method that re-builds it. You may use the method on your own risk to redraw the palette, conditionally showing or hiding palette entries.

Please approach us [on our forums](https://forum.bpmn.io/) to ask implementation related questions. If you provide more details on your use case (i.e. a mock-up of what you plan to implement) we may be able to provide you more appropriate solutions.

**Comment by kmanikandanmca2008** [comment]
Raised this help in forum
