### ISSUE TITLE
Is there a parameter configuration document for bpmnjs?

### ISSUE THREAD

**Issue by Super-Mumoo** [bpmn-io/bpmn-js-examples#89]
bpmnModeler = new BpmnJS({
            //some items
});

**Comment by philippfromme** [comment]
If you're asking for documentation about the possible options when creating a new bpmn-js instance, they are [documented in the source code](https://github.com/bpmn-io/bpmn-js/blob/master/lib/Viewer.js#L108).

In general you can specify options for each feature using its name. An example:

```javascript

// a feature
class MyFeature {
  constructor(config) {
    console.log(config.myOption);
  }
}

export default {
  __init__: [ 'myFeature' ],
  myFeature: [ 'type', MyFeature ]
}
```

```javascript
new BpmnJS({
  additionalModules: [
    myFeature
  ],
  myFeature: {
    myOption: 'foo'
  }
});
```
