### ISSUE TITLE
With bpmn-js-0.11 Unable to build Modeler example

### ISSUE THREAD

**Issue by venkatapathy** [bpmn-io/bpmn-js-examples#9]
I suspect some file names are changed like BpmnRenderer, Renderer util which are not changed in some files of Modeler, hence error is thrown when 'Grunt' is run. 
Error message is:

Running "browserify:watch" (browserify) task
>> Error: Cannot find module 'diagram-js/lib/util/RenderUtil' from '/home/venkat/phd/bpmn-js/bpmn-js-examples/modeler/node_modules/bpmn-js/lib/draw'
Warning: Error running grunt-browserify. Use --force to continue.

Note that the error does not occur when I change to 0.10.0 in package.json. So I suspect Aug 10 commit to bounce bpmn-js?

**Comment by nikku** [comment]
I cannot reproduce the issue you are seeing.

```
$ git clone git@github.com:bpmn-io/bpmn-js-examples.git
$ cd bpmn-js-examples
$ git checkout v0.11.0
$ cd modeler
$ npm install && grunt
>> Bundle dist/index.js created.
```

Make sure you are not running against an incompatible linked (i.e. master) version of bpmn-js or diagram-js. We introduced a few breaking changes with the upcoming version of the modeler.

**Comment by venkatapathy** [comment]
I run the same exact command as above but I still get the errors. Attaching the commandline output of my run.
Not sure if I should ask this question in forum or here so, for now sticking to this.

**Comment by venkatapathy** [comment]
I dug a little deeper. Seems, bpmn-js/lib/draw/BpmnRenderer.js requires diagram-js/lib/draw/BaseRendere.js, but diagram-js.v.0.11. seems to not have that file. But diagram-js- master branch has it. When I manually copied the error disappeared. I don't know how to correct it in the files, since I am very new to GitHub style of committing. Will wait for your feedback and also will watch what you do. Thanks.

**Comment by nikku** [comment]
You need to properly set up the latest versions of diagram-js and bpmn-js if you would like to work against our latest master. The [setup docs](https://github.com/bpmn-io/bpmn-js/blob/master/docs/project/SETUP.md#manual-steps) should give you some hints on how to do this.
