### ISSUE TITLE
run colors/index.html  bug

### ISSUE THREAD

**Issue by xhuihui** [bpmn-io/bpmn-js-examples#91]
run  colors/index.html  

 Uncaught TypeError: Cannot read property 'width' of undefined

**Comment by xhuihui** [comment]
`$.get('https://cdn.rawgit.com/bpmn-io/bpmn-js-examples/master/colors/resources/pizza-collaboration.bpmn', showDiagram);`

Modified to the following code

`$.get('https://cdn.rawgit.com/bpmn-io/bpmn-js-examples/master/colors/resources/pizza-collaboration.bpmn', showDiagram, 'text');`


Google Chrome  73.0.3683.103

**Comment by nikku** [comment]
Thanks for the notice.
