### ISSUE TITLE
use default properties panel and custom properties panel together

### ISSUE THREAD

**Issue by kavaan** [bpmn-io/bpmn-js-examples#94]
i wanna add a custom properties for start event or other elements, i use this example for default panel :
[properties-panel](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel)

and use this example for costume properties  :
[properties-panel-extension](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension)
how can i use costume and extension properties panel  together?(please help me, its very important for me) @philippfromme  @ricardomatias @zeropaper

**Comment by philippfromme** [comment]
For questions regarding our toolkit please head over to our [forum](https://forum.bpmn.io/).
