### ISSUE TITLE
How can I include the panel in a  Vanilla js + jquery site.

### ISSUE THREAD

**Issue by lghamie** [bpmn-io/bpmn-js-examples#98]
Hi there, I have a question regarding the instantiation of this module:

I'm currently requiring the modeler using:

<script src="https://unpkg.com/bpmn-js@4.0.1/dist/bpmn-modeler.development.js"></script>

And then i'm rendering a modeler like this:

```
	    var bpmnViewer = new BpmnJS({
	      container: '#xml_render'
	    });
```

How can I add this module using that type of syntax? I can't find a way to replace the "require" statement :
```
var propertiesPanelModule = require('bpmn-js-properties-panel'),

additionalModules: [
    propertiesPanelModule,
  ],
```

**Comment by yfwz100** [comment]
It seems that `bpmn-js-properties-panel` didn't includes a precompiled version in npm.
(https://unpkg.com/bpmn-js-properties-panel)

**Comment by nikku** [comment]
As mentioned by @yfwz100 we do not provide a pre-packaged distribution (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/270).

Because of that you cannot use the properties panel without packaging it yourself.

**Comment by JoeXin** [comment]
Is there a pre-packaged release?

**Comment by nikku** [comment]
Nope.

**Comment by devrebeleza** [comment]
Hi there, 
I was able to integrate bpmn.io to my Apex application using "https://unpkg.com/bpmn-js@10.2.0/dist/bpmn-modeler.production.min.js", and now I want to integrate the properties panel. 

Is there a possibility to use something like a prepackaged library for that? 

Thanks in advance
